### ISSUE TITLE
Architettura di base e file di configurazione

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#1]
L'ambiente di test dovrebbe essere il più possibile self-contained, ed eseguibile da shell come segue:

```
./spid-testenv.py
```

La configurazione dovrebbe avvenire in un file YAML contenente le seguenti informazioni:

* Configurazione dell'IdP:
   * entityID
   * path file chiave privata
   * path file certificato
   * ...altre informazioni necessarie al funzionamento dell'IdP
* Configurazione dei Service Provider da abilitare (più di uno), per ciascuno:
   * entityID
   * path file certificato
   * `AssertionConsumerService`
   * `AttributeConsumingService`
   * ...altre informazioni necessarie al riconoscimento del Service Provider
* Utenti di test, per ciascuno:
   * login/password
   * attributi primari e secondari definiti dalle regole SPID (codice fiscale, telefono ecc.)

**Comment by umbros** [comment]
La configurazione ok su un yaml ma necessaria un'interfaccia che lo crei.

**Comment by fmarco** [comment]
@umbros @alexrj vogliamo quindi adottare un parsing json al momento?

**Comment by alexrj** [comment]
@umbros, il supporto multiutente è tracciato in #6 e lo aggiungeremo come prima evoluzione. Ma come primo deliverable non è necessario

**Comment by umbros** [comment]
@fmarco possiamo adottare un parser json o comunque un parser, vista la natura stessa dello yaml, che possa parserizzare sia yaml sia json.

**Comment by fmarco** [comment]
@umbros sì, certo
