### ISSUE TITLE
Documentare creazione chiave

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#10]
Nel README bisogna riportare il seguente comando che consente di creare chiave e certificato per l'IdP:

```
openssl req -x509 -nodes -sha256 -days 365 -newkey rsa:2048 -keyout idp.key -out idp.crt
```

**Comment by fmarco** [comment]
@alexrj fixed in [https://github.com/italia/spid-testenv2/commit/6175870899e31068b8a875bd0b1570bc992d073a](commit)
