### ISSUE TITLE
Migliorare presentazione errori

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#111]
Al momento gli errori di validazione vengono presentati in più modi diversi, suppongo perché vengono generati da diversi pezzi di codice.
In alcuni casi viene mostrato un messaggio grande al centro della pagina; in altri viene generata una tabella che ha a sinistra l'elemento XML e a destra una lista con gli errori, senza alcuna formattazione grafica.

La formattazione grafica la possiamo anche preparare noi; a tale scopo sarebbe utile uniformare la presentazione secondo una logica unitaria.

Dobbiamo capire ad esempio se è utile mantenere la prima colonna della tabella o è sufficiente mostrare i messaggi discorsivi (lavorando un po' sulla loro formulazione).

**Comment by alexrj** [comment]
Attualmente gli errori vengono mostrati così:

![screen shot 2018-08-10 at 19 57 16](https://user-images.githubusercontent.com/594957/43973378-a4b7519e-9cd7-11e8-86fd-d5ba19a015df.png)

Facciamo alcune modifiche:

* Mostriamo solo gli errori rilevati, quindi togliamo quel "Validazione tramite XSD ✔️" e anche quel "Validazione Regole spid" (SPID sempre maiuscolo).
* Scriviamo questo testo: _"La AuthnRequest inviata presenta i seguenti errori:"_
* Allarghiamo la tabellina al 100% della larghezza del suo contenitore.
* Impostiamo `border: 1px solid black; border-collapse: collapse` per la tabellina, e un padding di 8px per le sue celle.
* Nella prima colonna della tabellina errori, possiamo togliere il prefisso del namespace (ad es. `saml:`)? È l'alias usato dal parser del testenv2, ma non è detto che coincida con l'alias usato nell'XML originale e questo potrebbe disorientare gli utenti non particolarmente pratici di XML.
* Spostiamo la visualizzazione della Request sotto gli errori (spaziata di 50px dalla tabella errori).
* Togliamo il toggle, che secondo me non è utile. Mostriamo direttamente sempre l'XML, magari con un font-size un po' più piccolo.  Inoltre proverei ad impostare `white-space: pre-wrap;` in modo da evitare lo scroll laterale.

Parlando invece del contenuto degli errori, in questo caso mi sarei aspettato di leggere i seguenti messaggi:
* `Issuer`:
   * _L'elemento contiene un valore non coincidente con l'entityID del Service Provider._
   * _L'attributo `NameQualifier` contiene un valore non coincidente con l'entityID del Service Provider._

Dobbiamo fare uno sforzo di presentare dei messaggi di errore discorsivi. Non sempre si possono generare in modo automatico.

**Comment by alexrj** [comment]
Così appare invece la validazione XSD al momento:

![screen shot 2018-08-10 at 21 21 50](https://user-images.githubusercontent.com/594957/43977201-9fcd17e8-9ce3-11e8-917f-bc4a390684b2.png)

Visto che i valori della prima colonna sono molto lunghi credo sia opportuno visualizzarli in un altro modo, ad esempio con una lista puntata a più livelli:

* selettore XPath (colonna sinistra)
   * errore (colonna destra)

E come dicevo sopra non espliciterei questa divisione tra XSD e regole SPID. Sono solo metodi alternativi che usiamo internamente; all'utente interessa avere una lista di errori.

**Comment by alranel** [comment]
Fatte ora:


![screen shot 2018-12-22 at 00 18 44](https://user-images.githubusercontent.com/594957/50367249-2cac8500-057f-11e9-8d50-22f5f15dd7b7.png)
