### ISSUE TITLE
Documentare file di configurazione

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#12]
Nel file di configurazione dobbiamo aggiungere dei commenti prima di ogni opzione per spiegare come va configurata.
Di seguito alcune cose non immediatamente chiare e che potrebbero confondere lo sviluppatore:

* *entityid*: non è chiaro se sia quello dell'IdP o del SP da testare
* *https*: non è chiaro se si riferisca all'IdP di test o in qualche modo al SP (ovviamente si riferisce al primo ma, ripeto, ad una prima lettura da parte di una persona non familiare con l'architettura di SPID, potrebbe sollevare l'interrogativo)
* *metadata*: non è chiaro che si tratti dei SP e non è chiara la distinzione tra local e remote

Inoltre sostituirei i vari placeholder come `<absolute-path>` con dei valori di default (ad es. `idp.key` e `idp.crt`) in modo da diminuire l'effort di configurazione richiesto tra il `git clone` e l'esecuzione. Mi aspetto che provando ad eseguire il testenv mi venga mostrato un errore friendly come _"Impossibile leggere la chiave privata dell'IdP di test: File 'idp.key' not found"_.

In realtà credo che possiamo tranquillamente distribuire una chiave privata e un certificato di default già nel repository.

**Comment by fmarco** [comment]
@alexrj ho aperto una PR in wip intanto, ho documentato i vari parametri, anche quelli qui citati #13 
Probabilmente chiave e certificato possono essere creati tramite il comando incluso nel README (ho allineato i nomi nel file yaml di esempio), però se vogliamo inserire un paio di file non ci sono problemi.

**Comment by fmarco** [comment]
@alexrj chiudo perchè si riferisce ad una PR mergiata.
