### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#129]
Al fine di abilitare lo scenario descritto in #6, dobbiamo aggiungere il supporto per registrare in un database le seguenti informazioni:

* metadata SP collegati agli utenti di cui al punto 1 (tali metadata saranno caricati in aggiunta a quelli configurati staticamente in config.yaml)
* utenti SPID (attualmente registrati in users.json)

Questo database può essere ad esempio un set di file JSON (come l'attuale users.json) oppure un PostgreSQL.

La modalità file/postgres si potrà selezionare dal config.yaml (con default: file).

Sarebbe opportuno che il testenv interrogasse il database in tempo reale ad ogni richiesta cercando il metadata corrispondete all'Issuer del messaggio entrante (a tale scopo la tabella dei metadata deve avere l'entityID come chiave primaria), in modo da evitare comandi di ricaricamento ad ogni aggiornamento della tabella.

**Comment by fmarco** [comment]
@alranel Ciao, domanda: in modalità "postgres" per i metadata continua ad esserci il supporto anche per file locali o remoti?

**Comment by alranel** [comment]
Questa funzionalità è stata implementata #198 che ho completato oggi.
