### ISSUE TITLE
Opzioni di configurazione sign_assertion e attribute_statement_on_response

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#13]
Ho un dubbio su due opzioni che trovo nel file di configurazione:

* `sign_assertion`
* `attribute_statement_on_response`

In quali casi può essere utile configurarle?

**Comment by fmarco** [comment]
@alexrj Essendo che pysaml2 permette di decidere se firmare oppure no i messaggi e includere o meno l'elemento AttributeStatement ho pensato di impostarli come parametri booleani.
`sign_assertion` volendo si può eliminare, mentre `attribute_statement_on_response` potrebbe servire nel caso si voglia simulare la presenza o meno dell'elemento AttributeStatement nella risposta.
Probabilmente sono superflui e possono essere gestiti direttamente nella issue #4

**Comment by alexrj** [comment]
Le Regole Tecniche SPID, che pongono restrizioni rispetto alle regole di SAML, impongono che i messaggi siano sempre firmati e che l'elemento `<AttributeStatement>` sia presente se sono stati richiesti attributi nella AuthnRequest. Quindi propongo di togliere entrambe le opzioni di configurazione e di attenerci sempre al comportamento previsto per SPID.
