### ISSUE TITLE
Interfaccia di backoffice

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#130]
L'interfaccia di backoffice consiste in:

* login SSO GItHub
* caricamento/modifica/eliminazione metadata SP collegati all'utente corrente
   * basta una textarea per caricare il metadata completo (con validazione), poi in futuro faremo un'interfaccia più guidata
* gestione utenti SPID collegati all'utente corrente

In config.yaml aggiungiamo le seguenti opzioni:

* `backoffice` (true/false): abilita/disabilita l'interfaccia di backoffice
* `github_sso`: contiene i dati per l'integrazione con GitHub

Nel database dobbiamo aggiungere anche una tabella per gli utenti del testenv.  I metadata SP, così come gli utenti SPID, potranno essere associati ad un utente (qualora creati via backoffice).

**Comment by fmarco** [comment]
@alranel confermato il login tramite github?

**Comment by alranel** [comment]
Per ora ci accontentiamo del supporto per PostgreSQL. Eventuali portali di caricamento self-service dei metadati diventano (almeno per ora) out-of-scope rispetto a questo progetto.
