### ISSUE TITLE
Interfaccia di amministrazione

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#131]
L'interfaccia di amministrazione deve consentire la gestione dei dati presenti nel database (utenti testenv, metadata SP, utenti SPID).

Per ora possiamo usare un generico tool di gestione database.

**Comment by fmarco** [comment]
@alranel Ciao, questa sezione è protetta da qualche forma di autenticazione? Se sì, di che tipo (e quali utenti sono autorizzati ad accedervi?)

**Comment by alranel** [comment]
Ad oggi abbiamo:

* un'interfaccia per l'aggiunta di utenti;
* un'interfaccia per la gestione (aggiunta/cancellazione) dei metadati SP quando gestiti da database.

Possiamo chiudere la issue.
