### ISSUE TITLE
Supportare wildcard per caricare tutti i metadati presenti (conf/*.xml)

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#134]
in attesa di #130 e #131, sarebbe comodo che il testenv2 semplicemente caricasse tutti i metadati SP che trova nella cartella conf; meglio ancora se con un watch sulla dir che li ricarica quando ne compaiono di nuovi oppure vengono cambiati 

mi spiego, noi adesso abbiamo un instanza pubblica di IdP basato su testenv2:
https://teamdigitale4.simevo.com/

tutti potrebbero facilmente registrare un nuovo SP con:
```
scp my_metadata.xml teamdigitale4.simevo.com:/srv/testenv2/conf/.
```

se non c'è il watch, devono anche riavviare il servizio:
```
ssh root@teamdigitale4.simevo.com systemctl restart testenv2
```

**Comment by alexrj** [comment]
Il supporto per wildcard nel parametro `metadata.local` del config.yaml sarebbe comodo.
Il watch per ora lo teniamo in bassa priorità perché è più importante #129

**Comment by bfabio** [comment]
@simevo Sorry to reference a closed issue, but you may be interested in #279 which has the side effect of implementing the other half of your request.
