### ISSUE TITLE
RequestedAttributes non validi in AuthnRequest

### ISSUE THREAD

**Issue by davidlibrera** [italia/spid-testenv2#143]
Se fornisco degli attributi non validi ricevo un application error di flask anziché una pagina di spiegazione dell'errore.

![screenshot from 2018-08-27 14-27-08](https://user-images.githubusercontent.com/400256/44659704-645a5480-aa05-11e8-8eee-6b9329da29bb.png)

**Comment by fmarco** [comment]
@davidlibrera si può chiudere questa? Dopo gli ultimi aggiornamenti non è più consentito esporre metadata contenententi attributi inesistenti (non sarà quindi possibile arrivare a trattare messaggi che li contengano).

**Comment by alranel** [comment]
Bisogna testare cosa succede se chiedo degli attributi non presenti nel metadata

**Comment by umbros** [comment]
@alranel Non si può verificare il caso perchè gli attributi sono definiti nel metadata e quindi la request riporta solo la index dell'Attribute Consuming Service. Se @fmarco ha integrato il controllo di rispondenza degli attributi richiedibili nel metadata, direi che si può chiudere la issue.
