### ISSUE TITLE
Codice fiscale non preceduto da TINIT-

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#150]
Il codice fiscale, restituito come attributo, deve essere sempre preceduto dalla stringa `TINIT-`.

**Comment by alexrj** [comment]
Forse la cosa più corretta è popolare i record di default direttamente con il prefisso TINIT- (e magari aggiungerlo automaticamente quando si inserisce da web un nuovo utente che non lo ha).

**Comment by fmarco** [comment]
@alexrj ho aperto una PR con fix + test, adesso il prefisso viene aggiunto sia alla generazione del file di default sia durante l'aggiunta via form
