### ISSUE TITLE
Livelli SPID implementati

### ISSUE THREAD

**Issue by TonyX360** [italia/spid-testenv2#151]
Salve,
ho notato che sul vecchio spid-test-env è possibile accedere solo con lvl1, questo nuovo ambiente fornisce anche accesso lvl 2 e 3?
Inoltre, è possibile effettuare il passaggio fra livelli SPID (es. 1 -> 2 ) ? 
E' sufficiente passare l'attributo "ForceAuth=true" nella SAML AuthnRequest? 

Grazie e buona serata,

**Comment by alexrj** [comment]
La risposta è sì. Ovviamente test e feedback sono benvenuti, visto che c'è molto lavoro in corso e quindi se manca qualcosa si corregge.

**Comment by TonyX360** [comment]
Perfetto, grazie per la pronta risposta! 
Potrei chiederti informazioni aggiuntive anche per quanto riguarda il passaggio fra livelli SPID?
E' sufficiente passare come attributo "ForceAuth=true" con il relativo AuthnContextClassRef nella SAML AuthnRequest?
