### ISSUE TITLE
Add docker-compose.yml

### ISSUE THREAD

**Issue by ioggstream** [italia/spid-testenv2#152]
## I wish

to have a docker-compose to build and run the container via

```
docker-compose up
```

## instead

I don't

**Comment by alexrj** [comment]
Why a docker-compose?

This package only needs a single Docker container.

**Comment by ioggstream** [comment]
compose can be a way to run containerized test, dev env & co without
installing multiple pythons locally

I'll PR an alternative patch creating dummy certs so we can run without a
compose

**Comment by peppelinux** [comment]
@ioggstream is there any news on this or do we have to close it gracefully? :)

**Comment by ioggstream** [comment]
I'd add a docker-compose :) Feel free to add it and close, or just close.
