### ISSUE TITLE
Add a parameter for generating self-signed certificates

### ISSUE THREAD

**Issue by ioggstream** [italia/spid-testenv2#153]
## I wish

to autogenerate self-signed certificate at server startup if they are missing

eg. `spid-testenv.py --dummy-cert`

## Notes

PR will come.

**Comment by alexrj** [comment]
I don't think we should have this in the testenv2. Creating a private key and a certificate is a one-line shell command. No actual benefit from running your proposed custom `spid-testenv.py --dummy-cert` instead of the usual `openssl req` command...

**Comment by ioggstream** [comment]
OK :)
