### ISSUE TITLE
AuthnRequest: attributo Destination non validato come da regole tecniche

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#158]
A causa di un refuso nelle regole tecniche (v. https://github.com/italia/spid-regole-tecniche/issues/20) è prescritto che l'attributo `Destination` della AuthnRequest contenga l'entityID dell'Identity Provider anziché l'URL del SingleSignOnService a cui si sta inviando la richiesta.

Al momento il testenv2 segue quest'ultimo criterio, conformemente con SAML, che purtroppo non è quello in vigore in SPID.

Dobbiamo quindi fare in modo che il testenv2 accetti solo il valore previsto dalle regole tecniche SPID, ovvero l'entityID dell'Identity Provider.

**Comment by fmarco** [comment]
@alexrj aperta pr con fix e test
