### ISSUE TITLE
Errore validazione AuthnRequest POST Binding

### ISSUE THREAD

**Issue by lorenzocattaneo** [italia/spid-testenv2#159]
Di seguito un esempio di AuthnRequest inviata (questo è quello che vedo dalla schermata di errore del testenv cliccando "Mostra Request"):

```XML
<?xml version="1.0"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="pfx73f437b5-adf8-9539-ee75-c6a9db284f76" Version="2.0" IssueInstant="2018-09-07T08:14:40Z" Destination="http://0.0.0.0:8088/sso" ForceAuthn="false" AssertionConsumerServiceIndex="0" AttributeConsumingServiceIndex="1">
   <saml:Issuer NameQualifier="https://sp.example.com" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://sp.example.com</saml:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
 <ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
   <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
 <ds:Reference URI="#pfx73f437b5-adf8-9539-ee75-c6a9db284f76"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>20nl5ILIwzj4pL3zQHl7o1LRjx2tBnXNs1x7V0FqFY4=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>QuGqC90kM6NLpxJRPPvkzM4nyuSqRTrtD/C6TB9g+mbfUybJPIVW1ZEGYh1tlb5gpMd84OToHTOG/EFldUrK0xIZfydd5z+4m30zGidjeCwCOByVck4RzjqfrV9Ka6LWoZ4UpwKwiiOHk1F85RvnD/NuKwob7B5VWUFh6wvBfrFhO8mBRr67i0lBCLjDe60kumn1FW9uWkBWrgO2QUs2lqE68RVM28kFmVE7cTend6L+3LgR6Fb/lUf2x0MU+z5+tagWNWexn9bIZPqko6TFZyoBSDf/NVJvTdT3G64FHOxHqOF7jtJ1ukdQHrSoJzFBVFgrGTQ/KKYIP3TZWPB52A==</ds:SignatureValue>
<ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIDJDCCAgwCCQDNsCsJBXTF4TANBgkqhkiG9w0BAQsFADBUMQswCQYDVQQGEwJJVDEOMAwGA1UECAwFSXRhbHkxDTALBgNVBAcMBFJvbWUxEjAQBgNVBAoMCW15c2VydmljZTESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTE4MDgzMDA4MzEwMFoXDTE5MDgzMDA4MzEwMFowVDELMAkGA1UEBhMCSVQxDjAMBgNVBAgMBUl0YWx5MQ0wCwYDVQQHDARSb21lMRIwEAYDVQQKDAlteXNlcnZpY2UxEjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ2XaYXnSdekzVkMnF3J6ea8AjUnQOghzz2TXUXlQU20EX9DV4zkTIiwea4IUVxk9nsGW7sueiqKdGPuD/NOHMwaKOfDwocq8D00yAgDKW7us7gdJ4EJC3ftVtYJ7kC2Bs315chdrD6g5gNap55hdsRKE3q4ljzRw72qOAkas5He4kaNHg5miurCfPEyd1tfqD4l5igt/Qgsfw5F141Z9eVM3fl5wNjgvbvLp0pbS9Gm9nXtVYRwpDid4yzDjrDCSREwFzSgrOV9bw+VCtmsyTPiNCwrHMDmyrg6VT4NcX487w81aA01z45kB5sNBf83Wc8E5lilJ7MkbUQ/22srZLkCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEASDsXbd/OjMVsyoJ63b+c7xc6EzmZP39tdToSTnlnSFYfsuYRZuUrKzEvo4GbB0jrkhhWK/ko/9QsLlr2OVRENUBzRepde9F9Ytw/E86lxGCghlGZ6vb1i1N3rDLP3b3OJ/hkF+DZyytfWPKdjsyQW0kVQW/cNFlRHKtdih4QcD/g8c2/gtCegtOljqmLxzmtfzUkGY1ka9gpJOwInRrD5zZ8claoqaDzD6+cmaoUUiM5eGS2osXJta/qQ98D9LfH1Vfn94VE4I0vVYHwXBnXNb2piO4YJNHLhAkCrbXdONAOmAqp6djpUShC1BrxsFJ2OHWIOs6COGsi3PKvGEbxCg==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature>
   <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
   <samlp:RequestedAuthnContext Comparison="exact">
       <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml:AuthnContextClassRef>
   </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```

che genera il seguente errore: 

Elemento 
```
xpath: {urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest/{http://www.w3.org/2000/09/xmldsig#}Signature
```
Dettagli errore
```
{u'text': None, u'attrs': {}, u'children': {'{http://www.w3.org/2000/09/xmldsig#}SignedInfo': {u'text': None, u'attrs': {}, u'children': {'{http://www.w3.org/2000/09/xmldsig#}CanonicalizationMethod': {u'text': None, u'attrs': {'Algorithm': 'http://www.w3.org/2001/10/xml-exc-c14n#'}, u'children': {}}, '{http://www.w3.org/2000/09/xmldsig#}SignatureMethod': {u'text': None, u'attrs': {'Algorithm': 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'}, u'children': {}}, '{http://www.w3.org/2000/09/xmldsig#}Reference': {u'text': None, u'attrs': {'URI': '#pfx73f437b5-adf8-9539-ee75-c6a9db284f76'}, u'children': {'{http://www.w3.org/2000/09/xmldsig#}DigestMethod': {u'text': None, u'attrs': {'Algorithm': 'http://www.w3.org/2001/04/xmlenc#sha256'}, u'children': {}}, '{http://www.w3.org/2000/09/xmldsig#}DigestValue': {u'text': '20nl5ILIwzj4pL3zQHl7o1LRjx2tBnXNs1x7V0FqFY4=', u'attrs': {}, u'children': {}}, '{http://www.w3.org/2000/09/xmldsig#}Transforms': {u'text': None, u'attrs': {}, u'children': {'{http://www.w3.org/2000/09/xmldsig#}Transform': {u'text': None, u'attrs': {'Algorithm': 'http://www.w3.org/2001/10/xml-exc-c14n#'}, u'children': {}}}}}}}}, '{http://www.w3.org/2000/09/xmldsig#}KeyInfo': {u'text': None, u'attrs': {}, u'children': {'{http://www.w3.org/2000/09/xmldsig#}X509Data': {u'text': None, u'attrs': {}, u'children': {'{http://www.w3.org/2000/09/xmldsig#}X509Certificate': {u'text': 'MIIDJDCCAgwCCQDNsCsJBXTF4TANBgkqhkiG9w0BAQsFADBUMQswCQYDVQQGEwJJVDEOMAwGA1UECAwFSXRhbHkxDTALBgNVBAcMBFJvbWUxEjAQBgNVBAoMCW15c2VydmljZTESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTE4MDgzMDA4MzEwMFoXDTE5MDgzMDA4MzEwMFowVDELMAkGA1UEBhMCSVQxDjAMBgNVBAgMBUl0YWx5MQ0wCwYDVQQHDARSb21lMRIwEAYDVQQKDAlteXNlcnZpY2UxEjAQBgNVBAMMCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ2XaYXnSdekzVkMnF3J6ea8AjUnQOghzz2TXUXlQU20EX9DV4zkTIiwea4IUVxk9nsGW7sueiqKdGPuD/NOHMwaKOfDwocq8D00yAgDKW7us7gdJ4EJC3ftVtYJ7kC2Bs315chdrD6g5gNap55hdsRKE3q4ljzRw72qOAkas5He4kaNHg5miurCfPEyd1tfqD4l5igt/Qgsfw5F141Z9eVM3fl5wNjgvbvLp0pbS9Gm9nXtVYRwpDid4yzDjrDCSREwFzSgrOV9bw+VCtmsyTPiNCwrHMDmyrg6VT4NcX487w81aA01z45kB5sNBf83Wc8E5lilJ7MkbUQ/22srZLkCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEASDsXbd/OjMVsyoJ63b+c7xc6EzmZP39tdToSTnlnSFYfsuYRZuUrKzEvo4GbB0jrkhhWK/ko/9QsLlr2OVRENUBzRepde9F9Ytw/E86lxGCghlGZ6vb1i1N3rDLP3b3OJ/hkF+DZyytfWPKdjsyQW0kVQW/cNFlRHKtdih4QcD/g8c2/gtCegtOljqmLxzmtfzUkGY1ka9gpJOwInRrD5zZ8claoqaDzD6+cmaoUUiM5eGS2osXJta/qQ98D9LfH1Vfn94VE4I0vVYHwXBnXNb2piO4YJNHLhAkCrbXdONAOmAqp6djpUShC1BrxsFJ2OHWIOs6COGsi3PKvGEbxCg==', u'attrs': {}, u'children': {}}}}}}, '{http://www.w3.org/2000/09/xmldsig#}SignatureValue': {u'text': 'QuGqC90kM6NLpxJRPPvkzM4nyuSqRTrtD/C6TB9g+mbfUybJPIVW1ZEGYh1tlb5gpMd84OToHTOG/EFldUrK0xIZfydd5z+4m30zGidjeCwCOByVck4RzjqfrV9Ka6LWoZ4UpwKwiiOHk1F85RvnD/NuKwob7B5VWUFh6wvBfrFhO8mBRr67i0lBCLjDe60kumn1FW9uWkBWrgO2QUs2lqE68RVM28kFmVE7cTend6L+3LgR6Fb/lUf2x0MU+z5+tagWNWexn9bIZPqko6TFZyoBSDf/NVJvTdT3G64FHOxHqOF7jtJ1ukdQHrSoJzFBVFgrGTQ/KKYIP3TZWPB52A==', u'attrs': {}, u'children': {}}}} extra keys not allowed
```

La stessa AuthnRequest senza firma XML, quindi con Binding HTTP Redirect, funziona correttamente. Ho provato a confrontare la firma con quella delle specifiche SAML 2.0 ma non mi sembra di trovare differenze. 
Sapreste darmi qualche indicazione?

**Comment by alexrj** [comment]
L'errore in effetti è incomprensibile, va tradotto in qualcosa di utile :-)

**Comment by fmarco** [comment]
@alexrj fixata da #180 

@lorenzocattaneo potresti riprovare con master aggiornato?

**Comment by lorenzocattaneo** [comment]
@fmarco Ho appena provato, tutto a posto. Login completato con successo 👍

**Comment by lorenzocattaneo** [comment]
UPDATE: ho fatto nuovi test e il problema è ancora in parte presente: ora la AuthnRequest passa ma non la LogoutRequest, ottengo lo stesso errore.
Dovrebbe trattarsi di un problema di validazione dal vostro lato, perchè usa la stessa identica firma per tutte le request, e se con AuthnRequest passa dovrebbe anche con le altre.

**Comment by marcoz-tsn** [comment]
@fmarco a me oltre all'errore segnalato ne dà altri 2:

Elemento | Dettagli errore
-- | --
xpath: {urn:oasis:names:tc:SAML:2.0:protocol}LogoutRequest - attribute: Reason | urn:oasis:names:tc:SAML:2.0:logout:user extra keys not allowed
xpath: {urn:oasis:names:tc:SAML:2.0:protocol}LogoutRequest - attribute: NotOnOrAfter | 2018-09-14T16:14:03.6077842Z extra keys not allowed
xpath: {urn:oasis:names:tc:SAML:2.0:protocol}LogoutRequest/{http://www.w3.org/2000/09/xmldsig#}Signature | {'attrs': {}, 'text': None, 'children': {'{http://www.w3.org/2000/09/xmldsig#}SignatureValue': {'attrs': {}, 'text': 'MdgHxsf0D2A69IRljt0q0oEGEcoMR9DMmemd7S5xjmcztnP8AT4n+aVIg4rmXQHt2uN4UUcODdLhZBg39ABkJa2vp1A4qYv1HdriB3jGzmwCsO2VTWzJaNT/o7edHjRnAPG+R04r3X05I8wcDrfd9qE8RxvJoV8oJ68m81TU0ob05i29UN1SMw+a+qLbvNRknSSSA5Efrzqb6+TDYGGGVipXpmU3cvlmUade7U7tiIBlucGUKjZLuddzKTvk5ec2YEzgH7Kq6qTRL05uWKgvgQCH/BHd/anekQhRVFg/lQxFuLpmgx5e1aYvUELeFpJ9x4/HOsHaKwRr5e/mdxZh+w==', 'children': {}}, '{http://www.w3.org/2000/09/xmldsig#}SignedInfo': {'attrs': {}, 'text': None, 'children': {'{http://www.w3.org/2000/09/xmldsig#}CanonicalizationMethod': {'attrs': {'Algorithm': 'http://www.w3.org/2001/10/xml-exc-c14n#'}, 'text': None, 'children': {}}, '{http://www.w3.org/2000/09/xmldsig#}Reference': {'attrs': {'URI': '#_55d5aaad-e828-4609-8c71-8064ea01cc91'}, 'text': None, 'children': {'{http://www.w3.org/2000/09/xmldsig#}DigestMethod': {'attrs': {'Algorithm': 'http://www.w3.org/2001/04/xmlenc#sha256'}, 'text': None, 'children': {}}, '{http://www.w3.org/2000/09/xmldsig#}Transforms': {'attrs': {}, 'text': None, 'children': {'{http://www.w3.org/2000/09/xmldsig#}Transform': {'attrs': {'Algorithm': 'http://www.w3.org/2001/10/xml-exc-c14n#'}, 'text': None, 'children': {}}}}, '{http://www.w3.org/2000/09/xmldsig#}DigestValue': {'attrs': {}, 'text': 'hO5K78sAxH3pK0L+ekkBx60w8gZGYWup734Y81efT7A=', 'children': {}}}}, '{http://www.w3.org/2000/09/xmldsig#}SignatureMethod': {'attrs': {'Algorithm': 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'}, 'text': None, 'children': {}}}}, '{http://www.w3.org/2000/09/xmldsig#}KeyInfo': {'attrs': {}, 'text': None, 'children': {'{http://www.w3.org/2000/09/xmldsig#}X509Data': {'attrs': {}, 'text': None, 'children': {'{http://www.w3.org/2000/09/xmldsig#}X509Certificate': {'attrs': {}, 'text': 'MIIEIDCCAwigAwIBAgIJAMloSujuBWCdMA0GCSqGSIb3DQEBCwUAMIGkMQswCQYDVQQGEwJJVDEPMA0GA1UECAwGVkVORVRPMQ8wDQYDVQQHDAZQQURPVkExEzARBgNVBAoMClRFQ1NJUyBzcmwxGzAZBgNVBAsMElJpY2VyY2EgZSBzdmlsdXBwbzEcMBoGA1UEAwwTd3d3LmlyaWRlLnRlY3Npcy5pdDEjMCEGCSqGSIb3DQEJARYUaW5mb0BpcmlkZS50ZWNzaXMuaXQwHhcNMTgwODAzMDgzMDMzWhcNMTkwODAzMDgzMDMzWjCBpDELMAkGA1UEBhMCSVQxDzANBgNVBAgMBlZFTkVUTzEPMA0GA1UEBwwGUEFET1ZBMRMwEQYDVQQKDApURUNTSVMgc3JsMRswGQYDVQQLDBJSaWNlcmNhIGUgc3ZpbHVwcG8xHDAaBgNVBAMME3d3dy5pcmlkZS50ZWNzaXMuaXQxIzAhBgkqhkiG9w0BCQEWFGluZm9AaXJpZGUudGVjc2lzLml0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA29JKIbjlqu15EsV7vezUQgbMe7jEYldZm+9mug6QN8Tr+FlVyEYnQPJCE65SRRHl5z2Nis9jy8Hx2vbhXiA8rIBvUu8u4kpNblosUmreeXYy/lW3+bu1cffiDILOGq7sBbaKN2i3pYt73CZ8l3K739FYd59Mhq6tKkSIVHNipuUHFuj/+cPNlTqgj8moZJEGI0kC9NmZdUF5c0lgrBsBohZYIpeUdhv/LEGJqHdhNRGVA+0EavNp2TUKXL7o4enpZTsol2C450T2CqSFfml1R0PyHAKrYISM2Op3ge2Su5ya8wcd3JzxVaCH2+vOQWGGu19ZIlzv1MufqDgtemVH8QIDAQABo1MwUTAdBgNVHQ4EFgQUWBGdgr9y5YoBAidF75hawB/0Q7YwHwYDVR0jBBgwFoAUWBGdgr9y5YoBAidF75hawB/0Q7YwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAWun7x5kXJrObtNHLKCHvGWmLPKXujapsI083jyB9GlhBxTAvP5NiBGPgTAc8SzD8zIhAe/CmvXGWSsg17jB7e4A9wT4KmQU7LN43mWw+2qJWLnu5EXxlm9yhVRJGRD4fQQjejwjZX0gQ63YTo9Ek3oTMQFd3NfWsgiFLeR66NTL/ScSddE8gUHr4/xIL4k80O1EXTdXzuIVjZGu0PEqYeUdNBUF3TkAGV+0YMQBCPSTDBr2Na/tGRo7c1Re+eCyMwNYmWs5bc4UXSigAS3Aj/qLzKWB/FAGvnYoa4ussqiJIySt7I5YdApVuUoyWnAWxH0cx8OMB8rldE6ACXQMk9g==', 'children': {}}}}}}}} extra keys not allowed

La request è:
`<?xml version="1.0"?><saml2p:LogoutRequest xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_55d5aaad-e828-4609-8c71-8064ea01cc91" Version="2.0" IssueInstant="2018-09-14T16:04:03.607Z" Destination="http://spid-testenv2:8088" Reason="urn:oasis:names:tc:SAML:2.0:logout:user" NotOnOrAfter="2018-09-14T16:14:03.6077842Z" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"><saml2:Issuer NameQualifier="http://www.iride.tecsis.it" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://www.iride.tecsis.it</saml2:Issuer><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" /><Reference URI="#_55d5aaad-e828-4609-8c71-8064ea01cc91"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" /><DigestValue>hO5K78sAxH3pK0L+ekkBx60w8gZGYWup734Y81efT7A=</DigestValue></Reference></SignedInfo><SignatureValue>MdgHxsf0D2A69IRljt0q0oEGEcoMR9DMmemd7S5xjmcztnP8AT4n+aVIg4rmXQHt2uN4UUcODdLhZBg39ABkJa2vp1A4qYv1HdriB3jGzmwCsO2VTWzJaNT/o7edHjRnAPG+R04r3X05I8wcDrfd9qE8RxvJoV8oJ68m81TU0ob05i29UN1SMw+a+qLbvNRknSSSA5Efrzqb6+TDYGGGVipXpmU3cvlmUade7U7tiIBlucGUKjZLuddzKTvk5ec2YEzgH7Kq6qTRL05uWKgvgQCH/BHd/anekQhRVFg/lQxFuLpmgx5e1aYvUELeFpJ9x4/HOsHaKwRr5e/mdxZh+w==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIEIDCCAwigAwIBAgIJAMloSujuBWCdMA0GCSqGSIb3DQEBCwUAMIGkMQswCQYDVQQGEwJJVDEPMA0GA1UECAwGVkVORVRPMQ8wDQYDVQQHDAZQQURPVkExEzARBgNVBAoMClRFQ1NJUyBzcmwxGzAZBgNVBAsMElJpY2VyY2EgZSBzdmlsdXBwbzEcMBoGA1UEAwwTd3d3LmlyaWRlLnRlY3Npcy5pdDEjMCEGCSqGSIb3DQEJARYUaW5mb0BpcmlkZS50ZWNzaXMuaXQwHhcNMTgwODAzMDgzMDMzWhcNMTkwODAzMDgzMDMzWjCBpDELMAkGA1UEBhMCSVQxDzANBgNVBAgMBlZFTkVUTzEPMA0GA1UEBwwGUEFET1ZBMRMwEQYDVQQKDApURUNTSVMgc3JsMRswGQYDVQQLDBJSaWNlcmNhIGUgc3ZpbHVwcG8xHDAaBgNVBAMME3d3dy5pcmlkZS50ZWNzaXMuaXQxIzAhBgkqhkiG9w0BCQEWFGluZm9AaXJpZGUudGVjc2lzLml0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA29JKIbjlqu15EsV7vezUQgbMe7jEYldZm+9mug6QN8Tr+FlVyEYnQPJCE65SRRHl5z2Nis9jy8Hx2vbhXiA8rIBvUu8u4kpNblosUmreeXYy/lW3+bu1cffiDILOGq7sBbaKN2i3pYt73CZ8l3K739FYd59Mhq6tKkSIVHNipuUHFuj/+cPNlTqgj8moZJEGI0kC9NmZdUF5c0lgrBsBohZYIpeUdhv/LEGJqHdhNRGVA+0EavNp2TUKXL7o4enpZTsol2C450T2CqSFfml1R0PyHAKrYISM2Op3ge2Su5ya8wcd3JzxVaCH2+vOQWGGu19ZIlzv1MufqDgtemVH8QIDAQABo1MwUTAdBgNVHQ4EFgQUWBGdgr9y5YoBAidF75hawB/0Q7YwHwYDVR0jBBgwFoAUWBGdgr9y5YoBAidF75hawB/0Q7YwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAWun7x5kXJrObtNHLKCHvGWmLPKXujapsI083jyB9GlhBxTAvP5NiBGPgTAc8SzD8zIhAe/CmvXGWSsg17jB7e4A9wT4KmQU7LN43mWw+2qJWLnu5EXxlm9yhVRJGRD4fQQjejwjZX0gQ63YTo9Ek3oTMQFd3NfWsgiFLeR66NTL/ScSddE8gUHr4/xIL4k80O1EXTdXzuIVjZGu0PEqYeUdNBUF3TkAGV+0YMQBCPSTDBr2Na/tGRo7c1Re+eCyMwNYmWs5bc4UXSigAS3Aj/qLzKWB/FAGvnYoa4ussqiJIySt7I5YdApVuUoyWnAWxH0cx8OMB8rldE6ACXQMk9g==</X509Certificate></X509Data></KeyInfo></Signature><saml2:NameID NameQualifier="http://www.iride.tecsis.it" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">id_08300a4f4edd3bbfead6b87cfb2449f7dcaf041c</saml2:NameID><saml2p:SessionIndex>id_25a2e734dd1c7cfab13efcc17b051e02789007f1</saml2p:SessionIndex></saml2p:LogoutRequest>
`

**Comment by fmarco** [comment]
@marcoz-tsn ho caricato un fix su master, potresti riprovare? Dovrebbero rimanere solo gli errori su Reason e NotOnOrAfter. @alexrj a proposito di questi due attributi, vanno esclusi o considerati opzionali?

**Comment by marcoz-tsn** [comment]
@fmarco ho ritestato: confermo la presenza dei soli errori relativi a Reason e NotOnOrAfter

**Comment by lorenzocattaneo** [comment]
@fmarco ho appena riprovato, ora il logout (sia POST che REDIRECT) causa un'eccezione, causata da
destination = _slo[0].get('Location')
response_binding = _slo[0].get('Binding')
rispettivamente riga 695 e 701 in server.py. 
Ho temporanteamente risolto così
destination = _slo.get('Location')
response_binding = _slo.get('Binding')

e, considerando questo fix, il logout POST funziona

**Comment by fmarco** [comment]
@lorenzocattaneo @marcoz-tsn riprovate pure con master aggiornato

**Comment by lorenzocattaneo** [comment]
@fmarco ok, completato login e logout POST con successo

**Comment by alexrj** [comment]
@fmarco, mi chiedevi in merito agli attributi Reason e NotOnOrAfter nella LogoutRequest. Su questi vale quello che dice lo standard SAML (che non ricordo ora a memoria): ti risultano obbligatori?
È in ogni caso fondamentale che i messaggi di errore siano comprensibili. Quelli che vedo sopra non lo sono molto, perché dicono che c'è un errore su quegli attributi ma non dice quale sia: sono mancanti? Sono presenti e invece non devono esserci? Sono non validi?

**Comment by sanjioh** [comment]
Corretta la validazione di `Reason` e `NotOnOrAfter` (https://github.com/italia/spid-testenv2/pull/192)
@alexrj E' vero che i messaggi d'errore al momento sono subottimali, sia a livello di espressivita' che di traduzione. L'idea e' quella di perfezionarli in un'iterazione dedicata, una volta che la logica di validazione e' stabile.
