### ISSUE TITLE
Errore di validazione SAMLRequest nel nodo Signature: extra keys not allowed

### ISSUE THREAD

**Issue by marcoz-tsn** [italia/spid-testenv2#165]
La seguente SAMLRequest, che fino a 2 settimane fa' veniva accettata:
`<?xml version="1.0" encoding="UTF-8"?>
<saml2p:AuthnRequest xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_72bb9cf9-53b2-4f2d-8540-c3c67b85faa7" Version="2.0" IssueInstant="2018-09-10T10:52:47.466Z" Destination="http://spid-testenv2:8088/sso" AssertionConsumerServiceIndex="0" AttributeConsumingServiceIndex="0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
	<saml2:Issuer NameQualifier="http://www.iride.tecsis.it" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://www.iride.tecsis.it</saml2:Issuer>
	<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
		<SignedInfo>
			<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
			<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
			<Reference URI="#_72bb9cf9-53b2-4f2d-8540-c3c67b85faa7">
				<Transforms>
					<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
					<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
				</Transforms>
				<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
				<DigestValue>D2ibSZP4IEyNOpIlCrZuGu3yFo5mVFF5qSUyzgW3A2w=</DigestValue>
			</Reference>
		</SignedInfo>
		<SignatureValue>fDj9...==</SignatureValue>
		<KeyInfo>
			<X509Data>
				<X509Certificate>MIIE...==</X509Certificate>
			</X509Data>
		</KeyInfo>
	</Signature>
	<saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
	<saml2:Conditions NotBefore="2018-09-10T10:50:47.466Z" NotOnOrAfter="2018-09-10T11:02:47.466Z" />
	<saml2p:RequestedAuthnContext Comparison="minimum">
		<saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef>
	</saml2p:RequestedAuthnContext>
</saml2p:AuthnRequest>`

restituisce l'errore:
xpath: {urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest/{http://www.w3.org/2000/09/xmldsig#}Signature

{
	'children': {
		'{http://www.w3.org/2000/09/xmldsig#}KeyInfo': {
			'children': {
				'{http://www.w3.org/2000/09/xmldsig#}X509Data': {
					'children': {
						'{http://www.w3.org/2000/09/xmldsig#}X509Certificate': {
							'children': {},
							'attrs': {},
							'text': 'MIIE...=='
						}
					},
					'attrs': {},
					'text': None
				}
			},
			'attrs': {},
			'text': None
		},
		'{http://www.w3.org/2000/09/xmldsig#}SignedInfo': {
			'children': {
				'{http://www.w3.org/2000/09/xmldsig#}SignatureMethod': {
					'children': {},
					'attrs': {
						'Algorithm': 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
					},
					'text': None
				},
				'{http://www.w3.org/2000/09/xmldsig#}Reference': {
					'children': {
						'{http://www.w3.org/2000/09/xmldsig#}DigestMethod': {
							'children': {},
							'attrs': {
								'Algorithm': 'http://www.w3.org/2001/04/xmlenc#sha256'
							},
							'text': None
						},
						'{http://www.w3.org/2000/09/xmldsig#}Transforms': {
							'children': {
								'{http://www.w3.org/2000/09/xmldsig#}Transform': {
									'children': {},
									'attrs': {
										'Algorithm': 'http://www.w3.org/2001/10/xml-exc-c14n#'
									},
									'text': None
								}
							},
							'attrs': {},
							'text': None
						},
						'{http://www.w3.org/2000/09/xmldsig#}DigestValue': {
							'children': {},
							'attrs': {},
							'text': 'TlxzUX6ERVpXELrhgp5DPyPEg740lfo+iZ/DlJ3t32E='
						}
					},
					'attrs': {
						'URI': '#_4fbebe38-1881-447e-87fd-205028d973c9'
					},
					'text': None
				},
				'{http://www.w3.org/2000/09/xmldsig#}CanonicalizationMethod': {
					'children': {},
					'attrs': {
						'Algorithm': 'http://www.w3.org/2001/10/xml-exc-c14n#'
					},
					'text': None
				}
			},
			'attrs': {},
			'text': None
		},
		'{http://www.w3.org/2000/09/xmldsig#}SignatureValue': {
			'children': {},
			'attrs': {},
			'text': 'UAAH...=='
		}
	},
	'attrs': {},
	'text': None
}
extra keys not allowed`

**Comment by alexrj** [comment]
Anche in questo caso dobbiamo rendere l'errore più comprensibile (non ho verificato se sia corretto o meno)

**Comment by alexrj** [comment]
@marcoz-tsn hai postato l'effettiva richiesta XML che stai inviando oppure hai troncato i valori delle firme prima di postarla qui su GitHub? I tag `<SignatureValue>` e `<X509Certificate>` sono chiaramente non validi

**Comment by marcoz-tsn** [comment]
@alexrj ho postato una versione coi valori troncati, era beninteso che ho validato l'xml a monte - per inciso proprio in quel sito - ed è valido. Ad ogni modo lo reincollo completo:

`<?xml version="1.0" encoding="UTF-8"?>
<saml2p:AuthnRequest xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_72bb9cf9-53b2-4f2d-8540-c3c67b85faa7" Version="2.0" IssueInstant="2018-09-10T10:52:47.466Z" Destination="http://spid-testenv2:8088/sso" AssertionConsumerServiceIndex="0" AttributeConsumingServiceIndex="0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
	<saml2:Issuer NameQualifier="http://www.iride.tecsis.it" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://www.iride.tecsis.it</saml2:Issuer>
	<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
		<SignedInfo>
			<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
			<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
			<Reference URI="#_72bb9cf9-53b2-4f2d-8540-c3c67b85faa7">
				<Transforms>
					<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
					<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
				</Transforms>
				<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
				<DigestValue>D2ibSZP4IEyNOpIlCrZuGu3yFo5mVFF5qSUyzgW3A2w=</DigestValue>
			</Reference>
		</SignedInfo>
		<SignatureValue>fDj9UzAv+xqEVCf8xh2L5M4Q5N8nWxnhcaAJZg7aZjmoUS9YEkf/e69zOumEN8vOFhEtEidg/RXhFYzUfh1ye/IhDYMD2pBFrrMYpq1pS3EYKJsZx+l+anuLj1dg4ZreGvIwvhV5fR2kQApIerE+nOUUnHACYkt0yhqJKaj7ayv+IzlKHASlOTqzpj2WXOgh53f9ExOM6AXxF9Eoppiwu/t1g5BfC1GKwA7MkQ+oNqwg8/L7vyugmiCuSaPwSFRE6ltL2klucZbQev+7rUjp2Dn20uQPfFHIdjhPQIQeSbj7fa5uLiglxMivMMGeC33+0FkjqoSTbJnjmV31OHLg/w==</SignatureValue>
		<KeyInfo>
			<X509Data>
				<X509Certificate>MIIEIDCCAwigAwIBAgIJAMloSujuBWCdMA0GCSqGSIb3DQEBCwUAMIGkMQswCQYDVQQGEwJJVDEPMA0GA1UECAwGVkVORVRPMQ8wDQYDVQQHDAZQQURPVkExEzARBgNVBAoMClRFQ1NJUyBzcmwxGzAZBgNVBAsMElJpY2VyY2EgZSBzdmlsdXBwbzEcMBoGA1UEAwwTd3d3LmlyaWRlLnRlY3Npcy5pdDEjMCEGCSqGSIb3DQEJARYUaW5mb0BpcmlkZS50ZWNzaXMuaXQwHhcNMTgwODAzMDgzMDMzWhcNMTkwODAzMDgzMDMzWjCBpDELMAkGA1UEBhMCSVQxDzANBgNVBAgMBlZFTkVUTzEPMA0GA1UEBwwGUEFET1ZBMRMwEQYDVQQKDApURUNTSVMgc3JsMRswGQYDVQQLDBJSaWNlcmNhIGUgc3ZpbHVwcG8xHDAaBgNVBAMME3d3dy5pcmlkZS50ZWNzaXMuaXQxIzAhBgkqhkiG9w0BCQEWFGluZm9AaXJpZGUudGVjc2lzLml0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA29JKIbjlqu15EsV7vezUQgbMe7jEYldZm+9mug6QN8Tr+FlVyEYnQPJCE65SRRHl5z2Nis9jy8Hx2vbhXiA8rIBvUu8u4kpNblosUmreeXYy/lW3+bu1cffiDILOGq7sBbaKN2i3pYt73CZ8l3K739FYd59Mhq6tKkSIVHNipuUHFuj/+cPNlTqgj8moZJEGI0kC9NmZdUF5c0lgrBsBohZYIpeUdhv/LEGJqHdhNRGVA+0EavNp2TUKXL7o4enpZTsol2C450T2CqSFfml1R0PyHAKrYISM2Op3ge2Su5ya8wcd3JzxVaCH2+vOQWGGu19ZIlzv1MufqDgtemVH8QIDAQABo1MwUTAdBgNVHQ4EFgQUWBGdgr9y5YoBAidF75hawB/0Q7YwHwYDVR0jBBgwFoAUWBGdgr9y5YoBAidF75hawB/0Q7YwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAWun7x5kXJrObtNHLKCHvGWmLPKXujapsI083jyB9GlhBxTAvP5NiBGPgTAc8SzD8zIhAe/CmvXGWSsg17jB7e4A9wT4KmQU7LN43mWw+2qJWLnu5EXxlm9yhVRJGRD4fQQjejwjZX0gQ63YTo9Ek3oTMQFd3NfWsgiFLeR66NTL/ScSddE8gUHr4/xIL4k80O1EXTdXzuIVjZGu0PEqYeUdNBUF3TkAGV+0YMQBCPSTDBr2Na/tGRo7c1Re+eCyMwNYmWs5bc4UXSigAS3Aj/qLzKWB/FAGvnYoa4ussqiJIySt7I5YdApVuUoyWnAWxH0cx8OMB8rldE6ACXQMk9g==</X509Certificate>
			</X509Data>
		</KeyInfo>
	</Signature>
	<saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
	<saml2:Conditions NotBefore="2018-09-10T10:50:47.466Z" NotOnOrAfter="2018-09-10T11:02:47.466Z" />
	<saml2p:RequestedAuthnContext Comparison="minimum">
		<saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef>
	</saml2p:RequestedAuthnContext>
</saml2p:AuthnRequest>`

**Comment by fmarco** [comment]
@alexrj fixata da #180 
@marcoz-tsn potresti riprovare con master aggiornato?

**Comment by marcoz-tsn** [comment]
Purtroppo dà ancora errore:

Elemento | Dettagli errore
-- | --
xpath: {urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest/{http://www.w3.org/2000/09/xmldsig#}Signature | {'children': {'{http://www.w3.org/2000/09/xmldsig#}SignatureValue': {'children': {}, 'attrs': {}, 'text': 'myK+CSLYzKX6nFeDuSPPGvIwHwdb7R0R3oZtSPlhzZ+FitZpCuLfA7cQ7DY4xy0dXLP6ozwNjDVJWlpZ6SouewYsx3z1i4xfwWCSBhXomVNS2guPo5fCIC7rKw+lShEG6ZtVZGStwutZ1H9tnaTe3tdy3rJGxkCn4vLPvrj5Wto+gjaMhLSGuHjPGSmgBlJs/SpOrZWDmnvrOtqrFXIDzru/RnkwtloVix4gErgiNzfAyRc89BtgDSsgq19L0njroLueir8SkMfwkpM+Mq8mx2fLb4S9310GDZYmUn+gMgcTB4aKsGhLkY3uRYh59I4zDEyQtc1FI9VmjQhN/TbGvA=='}, '{http://www.w3.org/2000/09/xmldsig#}SignedInfo': {'children': {'{http://www.w3.org/2000/09/xmldsig#}Reference': {'children': {'{http://www.w3.org/2000/09/xmldsig#}Transforms': {'children': {'{http://www.w3.org/2000/09/xmldsig#}Transform': {'children': {}, 'attrs': {'Algorithm': 'http://www.w3.org/2001/10/xml-exc-c14n#'}, 'text': None}}, 'attrs': {}, 'text': None}, '{http://www.w3.org/2000/09/xmldsig#}DigestValue': {'children': {}, 'attrs': {}, 'text': 'iVm8D7hR53tIi3MlAIyk15iOPrfWKh4UGmMLonmPfTQ='}, '{http://www.w3.org/2000/09/xmldsig#}DigestMethod': {'children': {}, 'attrs': {'Algorithm': 'http://www.w3.org/2001/04/xmlenc#sha256'}, 'text': None}}, 'attrs': {'URI': '#_693307d6-9e58-4212-8851-c8977d9f62c4'}, 'text': None}, '{http://www.w3.org/2000/09/xmldsig#}SignatureMethod': {'children': {}, 'attrs': {'Algorithm': 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'}, 'text': None}, '{http://www.w3.org/2000/09/xmldsig#}CanonicalizationMethod': {'children': {}, 'attrs': {'Algorithm': 'http://www.w3.org/2001/10/xml-exc-c14n#'}, 'text': None}}, 'attrs': {}, 'text': None}, '{http://www.w3.org/2000/09/xmldsig#}KeyInfo': {'children': {'{http://www.w3.org/2000/09/xmldsig#}X509Data': {'children': {'{http://www.w3.org/2000/09/xmldsig#}X509Certificate': {'children': {}, 'attrs': {}, 'text': 'MIIEIDCCAwigAwIBAgIJAMloSujuBWCdMA0GCSqGSIb3DQEBCwUAMIGkMQswCQYDVQQGEwJJVDEPMA0GA1UECAwGVkVORVRPMQ8wDQYDVQQHDAZQQURPVkExEzARBgNVBAoMClRFQ1NJUyBzcmwxGzAZBgNVBAsMElJpY2VyY2EgZSBzdmlsdXBwbzEcMBoGA1UEAwwTd3d3LmlyaWRlLnRlY3Npcy5pdDEjMCEGCSqGSIb3DQEJARYUaW5mb0BpcmlkZS50ZWNzaXMuaXQwHhcNMTgwODAzMDgzMDMzWhcNMTkwODAzMDgzMDMzWjCBpDELMAkGA1UEBhMCSVQxDzANBgNVBAgMBlZFTkVUTzEPMA0GA1UEBwwGUEFET1ZBMRMwEQYDVQQKDApURUNTSVMgc3JsMRswGQYDVQQLDBJSaWNlcmNhIGUgc3ZpbHVwcG8xHDAaBgNVBAMME3d3dy5pcmlkZS50ZWNzaXMuaXQxIzAhBgkqhkiG9w0BCQEWFGluZm9AaXJpZGUudGVjc2lzLml0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA29JKIbjlqu15EsV7vezUQgbMe7jEYldZm+9mug6QN8Tr+FlVyEYnQPJCE65SRRHl5z2Nis9jy8Hx2vbhXiA8rIBvUu8u4kpNblosUmreeXYy/lW3+bu1cffiDILOGq7sBbaKN2i3pYt73CZ8l3K739FYd59Mhq6tKkSIVHNipuUHFuj/+cPNlTqgj8moZJEGI0kC9NmZdUF5c0lgrBsBohZYIpeUdhv/LEGJqHdhNRGVA+0EavNp2TUKXL7o4enpZTsol2C450T2CqSFfml1R0PyHAKrYISM2Op3ge2Su5ya8wcd3JzxVaCH2+vOQWGGu19ZIlzv1MufqDgtemVH8QIDAQABo1MwUTAdBgNVHQ4EFgQUWBGdgr9y5YoBAidF75hawB/0Q7YwHwYDVR0jBBgwFoAUWBGdgr9y5YoBAidF75hawB/0Q7YwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAWun7x5kXJrObtNHLKCHvGWmLPKXujapsI083jyB9GlhBxTAvP5NiBGPgTAc8SzD8zIhAe/CmvXGWSsg17jB7e4A9wT4KmQU7LN43mWw+2qJWLnu5EXxlm9yhVRJGRD4fQQjejwjZX0gQ63YTo9Ek3oTMQFd3NfWsgiFLeR66NTL/ScSddE8gUHr4/xIL4k80O1EXTdXzuIVjZGu0PEqYeUdNBUF3TkAGV+0YMQBCPSTDBr2Na/tGRo7c1Re+eCyMwNYmWs5bc4UXSigAS3Aj/qLzKWB/FAGvnYoa4ussqiJIySt7I5YdApVuUoyWnAWxH0cx8OMB8rldE6ACXQMk9g=='}}, 'attrs': {}, 'text': None}}, 'attrs': {}, 'text': None}}, 'attrs': {}, 'text': None} extra keys not allowed

L'AuthnRequest è la seguente:
<?xml version="1.0"?><saml2p:AuthnRequest xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_693307d6-9e58-4212-8851-c8977d9f62c4" Version="2.0" IssueInstant="2018-09-14T14:00:05.057Z" Destination="http://spid-testenv2:8088/sso" AssertionConsumerServiceIndex="0" AttributeConsumingServiceIndex="0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"><saml2:Issuer NameQualifier="http://www.iride.tecsis.it" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://www.iride.tecsis.it</saml2:Issuer><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" /><Reference URI="#_693307d6-9e58-4212-8851-c8977d9f62c4"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" /><DigestValue>iVm8D7hR53tIi3MlAIyk15iOPrfWKh4UGmMLonmPfTQ=</DigestValue></Reference></SignedInfo><SignatureValue>myK+CSLYzKX6nFeDuSPPGvIwHwdb7R0R3oZtSPlhzZ+FitZpCuLfA7cQ7DY4xy0dXLP6ozwNjDVJWlpZ6SouewYsx3z1i4xfwWCSBhXomVNS2guPo5fCIC7rKw+lShEG6ZtVZGStwutZ1H9tnaTe3tdy3rJGxkCn4vLPvrj5Wto+gjaMhLSGuHjPGSmgBlJs/SpOrZWDmnvrOtqrFXIDzru/RnkwtloVix4gErgiNzfAyRc89BtgDSsgq19L0njroLueir8SkMfwkpM+Mq8mx2fLb4S9310GDZYmUn+gMgcTB4aKsGhLkY3uRYh59I4zDEyQtc1FI9VmjQhN/TbGvA==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIEIDCCAwigAwIBAgIJAMloSujuBWCdMA0GCSqGSIb3DQEBCwUAMIGkMQswCQYDVQQGEwJJVDEPMA0GA1UECAwGVkVORVRPMQ8wDQYDVQQHDAZQQURPVkExEzARBgNVBAoMClRFQ1NJUyBzcmwxGzAZBgNVBAsMElJpY2VyY2EgZSBzdmlsdXBwbzEcMBoGA1UEAwwTd3d3LmlyaWRlLnRlY3Npcy5pdDEjMCEGCSqGSIb3DQEJARYUaW5mb0BpcmlkZS50ZWNzaXMuaXQwHhcNMTgwODAzMDgzMDMzWhcNMTkwODAzMDgzMDMzWjCBpDELMAkGA1UEBhMCSVQxDzANBgNVBAgMBlZFTkVUTzEPMA0GA1UEBwwGUEFET1ZBMRMwEQYDVQQKDApURUNTSVMgc3JsMRswGQYDVQQLDBJSaWNlcmNhIGUgc3ZpbHVwcG8xHDAaBgNVBAMME3d3dy5pcmlkZS50ZWNzaXMuaXQxIzAhBgkqhkiG9w0BCQEWFGluZm9AaXJpZGUudGVjc2lzLml0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA29JKIbjlqu15EsV7vezUQgbMe7jEYldZm+9mug6QN8Tr+FlVyEYnQPJCE65SRRHl5z2Nis9jy8Hx2vbhXiA8rIBvUu8u4kpNblosUmreeXYy/lW3+bu1cffiDILOGq7sBbaKN2i3pYt73CZ8l3K739FYd59Mhq6tKkSIVHNipuUHFuj/+cPNlTqgj8moZJEGI0kC9NmZdUF5c0lgrBsBohZYIpeUdhv/LEGJqHdhNRGVA+0EavNp2TUKXL7o4enpZTsol2C450T2CqSFfml1R0PyHAKrYISM2Op3ge2Su5ya8wcd3JzxVaCH2+vOQWGGu19ZIlzv1MufqDgtemVH8QIDAQABo1MwUTAdBgNVHQ4EFgQUWBGdgr9y5YoBAidF75hawB/0Q7YwHwYDVR0jBBgwFoAUWBGdgr9y5YoBAidF75hawB/0Q7YwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAWun7x5kXJrObtNHLKCHvGWmLPKXujapsI083jyB9GlhBxTAvP5NiBGPgTAc8SzD8zIhAe/CmvXGWSsg17jB7e4A9wT4KmQU7LN43mWw+2qJWLnu5EXxlm9yhVRJGRD4fQQjejwjZX0gQ63YTo9Ek3oTMQFd3NfWsgiFLeR66NTL/ScSddE8gUHr4/xIL4k80O1EXTdXzuIVjZGu0PEqYeUdNBUF3TkAGV+0YMQBCPSTDBr2Na/tGRo7c1Re+eCyMwNYmWs5bc4UXSigAS3Aj/qLzKWB/FAGvnYoa4ussqiJIySt7I5YdApVuUoyWnAWxH0cx8OMB8rldE6ACXQMk9g==</X509Certificate></X509Data></KeyInfo></Signature><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" /><saml2:Conditions NotBefore="2018-09-14T13:58:05.057Z" NotOnOrAfter="2018-09-14T14:10:05.057Z" /><saml2p:RequestedAuthnContext Comparison="minimum"><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext></saml2p:AuthnRequest>

**Comment by fmarco** [comment]
@marcoz-tsn che binding stai utilizzando per inviare la AuthnRequest?

**Comment by marcoz-tsn** [comment]
POST binding

**Comment by marcoz-tsn** [comment]
Allora, per ora ho modificato ho modificato il mio fork di spid-dotnet-sdk in modo che non dia più il secondo errore, e così riesco ad autenticarmi anche se con i limiti dovuti a #164.
Direi che posso chiudere questa issue.
