### ISSUE TITLE
Algoritmo xml-c14n11 invece di xml-exc-c14n#

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#169]
In seguito a recenti modifiche, il testenv2 usa il metodo `http://www.w3.org/2006/12/xml-c14n11` invece di `http://www.w3.org/2001/10/xml-exc-c14n#` per trasformare i nodi da firmare.

Questo avviene perché è il metodo di default di signxml.XMLSigner. Si può modificare aggiungendo `c14n_algorithm='http://www.w3.org/2001/10/xml-exc-c14n#'` qui: https://github.com/italia/spid-testenv2/blob/10bde18eaafc662df287d6c21f74beb0d2b7dae1/testenv/crypto.py#L101-L104

Il fatto che si usi il metodo `xml-c14n11` non è di per sé un problema visto che, a quanto mi risulta, è accettato per SAML. Tuttavia mi sembra che venga generata una firma non valida per l'elemento `<Assertion>`. Confrontando l'XML canonicalizzato generato dal testenv2 con quello generato dalla mia implementazione client, c'è una differenza: nel primo caso l'elemento `<Assertion>` ha l'attributo `xmlns:samlp`, nel secondo no. Questo attributo è superfluo perché non c'è nessun elemento che necessita di quel namespace. Essendo i due XML differenti, i relativi digest escono differenti.

Tracciando il problema, sembra che il problema sia in `sign_http_post()`, laddove viene isolato l'elemento `<Assertion>`: etree aggiunge arbitrariamente l'attributo `xmlns:samlp`, qui superfluo, che invece nella struttura completa è definito solo a livello di elemento root.

Usando il metodo `xml-exc-c14n#` che è pensato apposta per i subdocument, il namespace superfluo viene rimosso durante la canonicalizzazione (a differenza di `xml-c14n11` che invece li preserva).

La soluzione più semplice è quella di usare `xml-exc-c14n#` (documentando nel codice il motivo per cui è necessario e aggiungendo un regression test).

(In aggiunta, `xml-c14n11 ` non è supportato da alcune librerie come ad esempio nodejs xml-crypto.

**Comment by fmarco** [comment]
@alexrj Grazie, molto interessante!

**Comment by alexrj** [comment]
@fmarco :-)

Abbiamo al momento un test che verifica la firma delle asserzioni?

**Comment by fmarco** [comment]
@alexrj al momento non c'è un test specifico per quella verifica, è anche vero che utilizzando una libreria esterna già testata e robusta ed essendo la response generata dal server stesso potrebbe trattarsi di un test "superfluo". Cosa ne pensi?

**Comment by alexrj** [comment]
@fmarco beh al momento la Response la genera il codice del testenv2, non usiamo più pysaml2. L'errore di questa issue ad esempio è esterno a signxml, o perlomeno il suo fix è in testenv2... se avessimo avuto una verifica sulla validità della firma questa regression non si sarebbe verificata. :)

**Comment by fmarco** [comment]
@alexrj Sì, hai ragione, conviene comunque aumentare la copertura (in vista anche del definitivo abbandono di pysaml2) aggiungo un regression test :+1:

**Comment by fmarco** [comment]
@pushato aggiunto test tramite pr #179
