### ISSUE TITLE
LogoutResponse: firma errata con il binding HTTP-Redirect

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#175]
La LogoutResponse generata dal testenv2 e inviata al Service Provider via binding HTTP-Redirect è firmata in modo non corretto.

L'errore è causato dall'errata costruzione della query string da firmare, al momento eseguita come segue:

https://github.com/italia/spid-testenv2/blob/78886652d398976f6a7c588bf78f31dba2c34745/testenv/crypto.py#L124-L140

Il valore assegnato a `query_string` è al momento:

```
RelayState=&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256
```

Ci sono due problemi:

1. Manca il parametro `SAMLResponse`.
2. Se `RelayState` è vuoto, non deve essere incluso.

**Comment by fmarco** [comment]
@alexrj aumentata copertura e aggiunti fix tramite #179
