### ISSUE TITLE
Aggiornamento dipendenza pysaml2

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#177]
GitHub segnala che la versione 4.5.0 di pysaml2 è considerata vulnerabile. Possiamo alzare la versione minima richiesta?

**Comment by fmarco** [comment]
@alexrj tieni conto che attualmente pysaml2 è utilizzata sempre meno e a momenti verrà totalmente rimossa

**Comment by alexrj** [comment]
Perfetto. Lascio questa issue aperta come promemoria

**Comment by alexrj** [comment]
Perfetto, chiudo la issue
