### ISSUE TITLE
Validazione ai fini dell'onboarding

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#19]
È in corso il lavoro di sviluppo di un portale di onboarding rivolto ai SP per gestire tutti i flussi di adesione alla federazione SPID, modifica dei servizi attivi, pubblicazione dei metadati.
In questo portale è prevista una fase di validazione tecnica dei servizi caricati prima che questi vadano in produzione nella federazione SPID.
A tale scopo bisogna integrare nel portale in corso di sviluppo questo IdP di test in modo da poter raccogliere l'esito dei test.

Di fatto ci saranno tre possibili scenari d'uso per questo IdP di test:
1. Si potrà eseguire in locale o su proprio server (a fini di studio, sviluppo, demo).
2. Si potrà usare in versione hosted, liberamente da parte di chiunque (sempre a fini di studio, sviluppo, demo).
3. Si potrà usare nell'ambito del processo di onboarding al fine di eseguire la validazione di un servizio.

Lo scenario 1, che al momento è già coperto, richiede la massima facilità di configurazione ed esecuzione. Non richiede un'interfaccia web per la creazione degli SP perché è sufficiente chiamare i metadati dal file di configurazione.

Gli scenari 2 e 3 prevedono che l'IdP di test sia erogato centralmente da AgID su propri server, ma con alcune differenze.
Nello scenario 2 serve un'interfaccia web in cui gli utenti (che possono essere anche semplici cittadini) possano configurare uno o più SP. L'accesso a questa interfaccia web potrebbe essere protetto semplicemente con un accesso GitHub in modo che ciascun utente veda i suoi SP. Deve essere a tutti gli effetti una sandbox, senza legami con il portale di onboarding.

Nello scenario 3 invece devono poter operare solo i soggetti già registrati nel portale di onboarding, e devono poter caricare solo i servizi che stanno validando/caricando nello stesso portale di onboarding. Inoltre il portale di onboarding deve avere accesso alle informazioni sui test eseguiti. In questo scenario non serve un'interfaccia web per la configurazione dei SP perché li creerebbe d'ufficio il portale di onboarding usando ad esempio delle API o un database.

Per lo scenario 2 serve un database per la persistenza delle utenze e dei metadati SP creati a runtime. Per lo scenario 3 si potrebbero esporre delle API per caricare i metadati relativi agli SP da validare (non serve che siano associati ad utenze), per modificarli, per cancellarli.
Inoltre bisogna poter abilitare il logging nel database finalizzato ad esporre, sempre tramite API, i risultati dei test in modo che il portale di onboarding possa usarli a fini di validazione.

Le informazioni da loggare (con XML completo ed eventuali warning rilevati dal testenv) sono:
* AuthnRequest ricevute con successo;
* LogoutRequest ricevute con successo (SP-initiated logout);
* LogoutResponse ricevute con successo (IdP-initiated logout).

È importante evitare il conflitto di entityID tra quelli caricati dall'interfaccia pubblica e quelli in validazione: questi ultimi devono sempre avere la precedenza. Probabilmente conviene separare gli scenari 2 e 3 in due installazioni diverse.

**Comment by alexrj** [comment]
Vedere anche issue #6.

@umbros suggerisce che nello scenario 2 si usi l'accesso SPID anziché GitHub. C'è sicuramente il vantaggio di immagine dell'"eat your own dog food", ma porta alcune scomodità: un soggetto privato non potrebbe installare in locale il testenv in modalità multiutente senza accreditarlo come SP in SPID ed inoltre bisognerebbe aggiungere il logging delle asserzioni per rispettare le regole tecniche.
Nello scenario 2 in realtà non c'è bisogno di identificare il soggetto, l'uso del servizio sarebbe libero... Nello scenario 3 il soggetto lo identifichiamo nel portale di onboarding e le utenze sull'IdP di test le attiviamo via API a valle di quella identificazione. Ne parliamo di persona

**Comment by fmarco** [comment]
@alexrj @umbros in tutti e tre i casi viene condivisa quindi la stessa codebase immagino, è corretto?
Potrebbe aver senso avere un pacchetto python, sempre autocontenuto, ma configurabile in qualche modo (che siano variabili di ambiente e/o file di configurazione come avviene attualmente) a seconda del tipo di scenario.
Per lo scenario 2 anche io sarei per un login tramite github (o qualcosa di simile), se ne può però discutere :) (anzi, andrà fatto).

Concordo sul separare gli scenari 2 e 3, probabilmente semplifica la gestione dei due ambienti.

**Comment by alexrj** [comment]
@fmarco, sì, sarebbe opportuno che fosse lo stesso pacchetto configurabile.

**Comment by alexrj** [comment]
@fmarco, puoi procedere con questa attività?

**Comment by fmarco** [comment]
l'idea è di procedere tramite una modularizzazione dell'applicativo, in modo che si adatti ai 3 ambienti, il codice sia facilmente manutenibile e rimanga al tempo stesso eseguibile tramite un singolo comando, da shell.
