### ISSUE TITLE
Location SSO e SLO Metadata

### ISSUE THREAD

**Issue by lorenzocattaneo** [italia/spid-testenv2#193]
Nei metadati generati il valore Location per i vari endpoint SSO e SLO contiene solo l'indirizzo relativo e non quello completo. In sostanza il base_url definito nel config non viene considerato.

Ho provato, nel config, a scrivere l'url completo nei campi degli endpoint SSO e SLO ma ricevo un errore perchè i path non sono relativi e non iniziano con /

I path dovrebbero quindi essere composti da base_url + endpoint, come tra l'altro succede sugli IDP "reali"

**Comment by simevo** [comment]
Questo nuovo tipo di metadati è stato introdotto dal commit ceca8926871402360d914b9c5144dc53f859274d

Leggendo la specifica SAML per l'[elemento `SingleSignOnService`](http://www.datypic.com/sc/saml2/e-md_SingleSignOnService.html) e per [la definizione del tipo `xsd:anyURI`](http://www.datypic.com/sc/xsd/t-xsd_anyURI.html) si vede che in effetti _formalmente_ l'attributo location può essere assoluto o negativo.

Tuttavia come nota @lorenzocattaneo è "prassi" indicare l'url assoluta:

entity_id | slo
---- | ----
https://identity.infocert.it | https://identity.infocert.it/spid/samlslo
https://posteid.poste.it | https://posteid.poste.it/jod-fs/sloservicepost
https://login.id.tim.it/affwebservices/public/saml2sso | https://login.id.tim.it/affwebservices/public/saml2slo
https://identity.sieltecloud.it | https://identity.sieltecloud.it/simplesaml/saml2/idp/SLS.php
https://loginspid.aruba.it | https://loginspid.aruba.it/ServiceLogoutRequest
https://idp.namirialtsp.com/idp | https://idp.namirialtsp.com/idp/profile/SAML2/POST/SLO
https://spid.register.it | https://spid.register.it/login/singleLogout
https://spid.intesa.it | https://spid.intesa.it/Time4UserServices/services/idp/SingleLogout

come avviene anche nelle regole tecniche SPID pag. 18: 
```
<md:SingleSignOnService
  Location="https://spidIdp.idpProvider.it/redirect-Post-saml2sso"
  Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"/>
<md:SingleSignOnService
  Location="https://spidIdp.idpProvider.it/Post-Post-saml2sso"
  Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"/>
```

Usare l'entity_id come base url per gli altri endpoint indicati nel metadata come url relative è un'interpretazione non supportata da alcuno standard.

Tant'è che per alcuni IdP di produzione l'entityID *non è* base_url per alcuni endpoint:
- per Poste ID, l'entityID usa il protocollo `https` mentre l'endpoint dei metadati usa il protocollo `http`
- per Tim ID, la stringa dell'entity ID (`https://login.id.tim.it/affwebservices/public/saml2sso`) non è contenuta in nessuno degli endpoint (`https://login.id.tim.it/spid-services/MetadataBrowser/idp`, `https://login.id.tim.it/affwebservices/public/saml2slo` e `https://login.id.tim.it/affwebservices/public/saml2sso`)
