### ISSUE TITLE
Login di base

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#2]
Il primo passo dovrebbe essere l'implementazione completa di un flusso di login:

* L'IdP di test riceve la AuthnRequest e la valida;
* mostra la schermata di login chiedendo login e password;
* mostra la schermata di autorizzazione al trasferimento degli attributi;
* confeziona la Response/Assertion e ritorna al Service Provider chiamante.

Questa attività dovrebbe supportare tutte le modalità previste dalle Regole Tecniche SPID, ovvero HTTP-Redirect e HTTP-POST.

Non essendo prevista, in quesa fase iniziale, la diagnostica dettagliata sulla correttezza dei messaggi in ingresso, si può usare anche una libreria pronta come PySAML o onelogin.
Quando, nella fase successiva, si andrà ad implementare anche la diagnostica dettagliata sui messaggi (ad esempio, presenza degli attributi, certificato scaduto ecc.) probabilmente non sarà più possibile usare una libreria esistente perché non offrirebbe la granularità necessaria nella validazione, ma sarà necessario reimplementare direttamente il parsing e la validazione.

**Comment by umbros** [comment]
Utilizzare in questa prima fare la libreria PySAML2 che è migliore rispetto a quella di onelogin ed è più facilmente gestibile per successive implementazioni.
Prevedere anche il flusso di livello 2 e, per la versione offline del sistema stampare l'OTP sulla schermata di 2factorauth, mentre per la versione online utilizzare un tool come google authenticator.

**Comment by fmarco** [comment]
@umbros attualmente il codice iniziale è basato proprio su pysaml2 :+1:
