### ISSUE TITLE
Consentire l'uso di URN come entityID

### ISSUE THREAD

**Issue by usumfabricae** [italia/spid-testenv2#203]
Nella registrazione del mio SP ho la necessità di inserire nel EntityID del Metadata provider un URI nel formato URN (urn:example:org)
 
Secondo specifiche SAML deve essere tra i formati supportati (http://www.datypic.com/sc/xsd/t-xsd_anyURI.html ), tuttavia mi accorgo che l'unico fomramto che sembra essere supportato è quello dell'URL.

**Comment by alranel** [comment]
L'osservazione è corretta: né le specifiche SAML né le regole tecniche SPID restringono l'entityID ad un URL.

**Comment by usumfabricae** [comment]
E' prevista una data per la fix ?

**Comment by peppelinux** [comment]
Per SPID l'entityID deve essere URI e contenere https.
Leggo dalle unità di test AgID di spi-saml-check

"The entityID attribute must be a valid HTTPS url"
