### ISSUE TITLE
Whitespace non ignorato nella validazione dell'elemento <Issuer>

### ISSUE THREAD

**Issue by enrichman** [italia/spid-testenv2#204]
Partendo da un'installazione pulita, ho creato e configurato il necessario seguendo il README:

```bash
mkdir -p ~/spid-testenv2/conf
cd ~/spid-testenv2
openssl req -x509 -nodes -sha256 -subj '/C=IT' -newkey rsa:2048 -keyout conf/idp.key -out conf/idp.crt
```

Ho copiato il file [config.yaml.example](https://raw.githubusercontent.com/italia/spid-testenv2/master/conf/config.yaml.example) scommentando la parte relativa al caricamento dei metadata del Service Provider:

```yaml
metadata:
  local:
  - "./conf/sp_metadata.xml"
```

Ho quindi generato il file `sp_metadata.xml` con il tool presente su https://idp.spid.gov.it:8080, inserendo il certificato generato precedentemente ed utilizzando `https://myserviceprovider.it/` come entityID.

A questo punto avvio il docker container con: 

```
docker run -it --rm --name spid-testenv2 -p 8088:8088 -v ~/spid-testenv2/conf:/app/conf italia/spid-testenv2
```

All'avvio il service provider è visibile in lista:

<img width="814" alt="screenshot 2018-12-02 at 10 53 30" src="https://user-images.githubusercontent.com/1763949/49338378-98569e80-f620-11e8-9c21-d5fe13ae47c1.png">

Ho encodato l'[xml di esempio](https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html#esempio-di-authnrequest) della guida in Base64, sostituendo:
`https://spid.identityprovider.it` -> `http://localhost:8088`
`http://spid.serviceprovider.it` -> `https://myserviceprovider.it/`

ed ho effettuato una POST verso `http://0.0.0.0:8088/sso` con due parametri, `SAMLRequest`, contenente l'xml encodato, e il parametro `RelayState` con una stringa casuale.

L'errore ritornato è:
> entity ID https://myserviceprovider.it/ non registrato

**Comment by marcoalbarelli** [comment]
Ciao
giusto per riferimento potresti postare anche il metadata completo dell'SP e la richiesta che mandi?
L'unica cosa che spicca è che dici di aver usato il certificato dell'IDP nel creare il metadata dell'SP
In teoria non dovrebbe dare cmq problemi

**Comment by alranel** [comment]
Confermo che riesco a riprodurre il comportamento con il comando `curl` da te indicato.
Invece cambiando il comando come segue funziona:

```bash
curl -X POST \
  http://localhost:8088/sso \
  -F 'SAMLRequest=PHNhbWxwOkF1dGhuUmVxdWVzdCB4bWxuczpzYW1scD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIgogICAgeG1sbnM6c2FtbD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIKICAgIElEPSJfNGQzOGMzMDI2MTdiNWJmOTg5NTFlNjViNGNmMzA0NzExZTIxNjZkZjIwIgogICAgVmVyc2lvbj0iMi4wIgogICAgSXNzdWVJbnN0YW50PSIyMDE1LTAxLTI5VDEwOjAwOjMxWiIKICAgIERlc3RpbmF0aW9uPSJodHRwOi8vbG9jYWxob3N0OjgwODgiCiAgICBBc3NlcnRpb25Db25zdW1lclNlcnZpY2VVUkw9Imh0dHBzOi8vbXlzZXJ2aWNlcHJvdmlkZXIuaXQvIgogICAgUHJvdG9jb2xCaW5kaW5nPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YmluZGluZ3M6SFRUUC1QT1NUIgogICAgQXR0cmlidXRlQ29uc3VtaW5nU2VydmljZUluZGV4PSIxIj4KICAgIDxzYW1sOklzc3VlcgogICAgICAgIE5hbWVRdWFsaWZpZXI9Imh0dHBzOi8vbXlzZXJ2aWNlcHJvdmlkZXIuaXQvIgogICAgICAgIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5Ij4KICAgICAgICBodHRwczovL215c2VydmljZXByb3ZpZGVyLml0LwogICAgPC9zYW1sOklzc3Vlcj4KICAgIDxzYW1scDpOYW1lSURQb2xpY3kgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDp0cmFuc2llbnQiIC8%2BCiAgICA8c2FtbHA6UmVxdWVzdGVkQXV0aG5Db250ZXh0IENvbXBhcmlzb249ImV4YWN0Ij4KICAgICAgICA8c2FtbDpBdXRobkNvbnRleHRDbGFzc1JlZj4KICAgICAgICAgICAgaHR0cHM6Ly93d3cuc3BpZC5nb3YuaXQvU3BpZEwyCiAgICAgICAgPC9zYW1sOkF1dGhuQ29udGV4dENsYXNzUmVmPgogICAgPC9zYW1scDpSZXF1ZXN0ZWRBdXRobkNvbnRleHQ%2BCjwvc2FtbHA6QXV0aG5SZXF1ZXN0Pg%3D%3D' \
  -F 'RelayState=_69f6bfc-33c1-46a7-9601-a0c9d1715eda'
```

A livello di richiesta HTTP la differenza è che l'ultimo comando genera un header `Content-Type: multipart/form-data`.

**Comment by alranel** [comment]
Né SAML né le regole di SPID dicono nulla rispetto all'uso di `application/x-www-form-urlencoded` o `multipart/form-data` quindi il testenv2 dovrebbe supportarle entrambe. Bisogna capire perché il primo non funziona e genera l'errore sull'entityID.

Intanto ti consiglierei di usare in ogni caso un browser per mandare le POST, perché è più comodo leggere gli errori restituiti dal testenv2. :)

**Comment by enrichman** [comment]
@alranel in realtà io ho l'errore anche con la tua richiesta. Mi dà diversi errori di encoding.
L'unica differenza è che nella tua SamlRequest i `+` e `==` sono escapati.

**Comment by alranel** [comment]
Hai ragione. La chiamata corretta quindi è:

```bash
curl -vvv -X POST \
  http://localhost:8088/sso \
  -F 'SAMLRequest=PHNhbWxwOkF1dGhuUmVxdWVzdCB4bWxuczpzYW1scD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIgogICAgeG1sbnM6c2FtbD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIKICAgIElEPSJfNGQzOGMzMDI2MTdiNWJmOTg5NTFlNjViNGNmMzA0NzExZTIxNjZkZjIwIgogICAgVmVyc2lvbj0iMi4wIgogICAgSXNzdWVJbnN0YW50PSIyMDE1LTAxLTI5VDEwOjAwOjMxWiIKICAgIERlc3RpbmF0aW9uPSJodHRwOi8vbG9jYWxob3N0OjgwODgiCiAgICBBc3NlcnRpb25Db25zdW1lclNlcnZpY2VVUkw9Imh0dHBzOi8vbXlzZXJ2aWNlcHJvdmlkZXIuaXQvIgogICAgUHJvdG9jb2xCaW5kaW5nPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YmluZGluZ3M6SFRUUC1QT1NUIgogICAgQXR0cmlidXRlQ29uc3VtaW5nU2VydmljZUluZGV4PSIxIj4KICAgIDxzYW1sOklzc3VlcgogICAgICAgIE5hbWVRdWFsaWZpZXI9Imh0dHBzOi8vbXlzZXJ2aWNlcHJvdmlkZXIuaXQvIgogICAgICAgIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5Ij4KICAgICAgICBodHRwczovL215c2VydmljZXByb3ZpZGVyLml0LwogICAgPC9zYW1sOklzc3Vlcj4KICAgIDxzYW1scDpOYW1lSURQb2xpY3kgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDp0cmFuc2llbnQiIC8+CiAgICA8c2FtbHA6UmVxdWVzdGVkQXV0aG5Db250ZXh0IENvbXBhcmlzb249ImV4YWN0Ij4KICAgICAgICA8c2FtbDpBdXRobkNvbnRleHRDbGFzc1JlZj4KICAgICAgICAgICAgaHR0cHM6Ly93d3cuc3BpZC5nb3YuaXQvU3BpZEwyCiAgICAgICAgPC9zYW1sOkF1dGhuQ29udGV4dENsYXNzUmVmPgogICAgPC9zYW1scDpSZXF1ZXN0ZWRBdXRobkNvbnRleHQ+Cjwvc2FtbHA6QXV0aG5SZXF1ZXN0Pg==' \
  -F 'RelayState=_69f6bfc-33c1-46a7-9601-a0c9d1715eda'
```

e genera un risultato uguale alla chiamata `application/x-www-form-urlencoded`. Avevo erroneamente interpretato la lunga lista di errori come uno step di validazione successivo.

**Comment by alranel** [comment]
Trovato il problema. Il tuo tag `<Issuer>` contiene spazi bianchi prima e dopo la URI. Questo è quanto indicato nell'esempio presente nelle regole tecniche SPID, quindi non è un tuo errore.
Credo che il testenv debba ignorarli, dobbiamo verificare e nel caso applicare un fix.

In ogni caso adesso aggiungo delle belle virgolette nel messaggio di errore, che avrebbero aiutato a capire la cosa immediatamente.

**Comment by alranel** [comment]
Sto cercando di capire se il whitespace debba essere ignorato al momento del parsing oppure no e questi sono gli elementi che ho raccolto:

* in diversi esempi SAML che ho trovato, il whitespace è presente (come nelle regole SPID);
* il [validatore di samltool.com](https://www.samltool.com/validate_authn_req.php) ignora il whitespace e considera valida la richiesta;
* l'elemento `<saml:Issuer>` è di tipo `saml:NameIDType`, il cui contenuto è definito come `xsd:string` che invece prescrive la *conservazione* del whitespace (diversamente da un tipo `xsd:anyURI` ad esempio che lo ignora);
* [SAML.Core](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) [8.3.6] dice che la sintassi di `<Issuer>` è una URI nel caso in cui si abbia `Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"`, tuttavia non dice esplicitamente che anche a livello di parsing si debba reinterpretare il valore come `xsd:anyURI` a tutti gli effetti.

Se da un lato il testenv2 deve essere sufficientemente restrittivo da garantire l'interoperabilità con gli IdP SPID, non possiamo essere inutilmente restrittivi rispetto ad una implementazione SAML generica. Vorrei quindi trovare qualche ulteriore riferimento su come dobbiamo comportarci.

**Comment by alranel** [comment]
L'elemento `<saml:Issuer>` è di tipo `saml:NameIDType`, il cui contenuto è definito come `xsd:string` la cui policy rispetto al whitespace è `preserve`, che mantiene gli spazi intermedi ed elimina quelli intorno alla stringa. Quindi questo è effettivamente un bug del testenv2.

**Comment by alranel** [comment]
Fixed.

**Comment by enrichman** [comment]
Grazie mille @alranel !
