### ISSUE TITLE
Problema nella validazione della AuthnRequest

### ISSUE THREAD

**Issue by pmosini** [italia/spid-testenv2#206]
Salve, quando provo ad efffetuare il SSO con l'IDP ottengo in risposta i seguenti errori di validazione:

**xpath: {urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest - attribute: Destination http://0.0.0.0:8088/sso è diverso dal valore di riferimento http://0.0.0.0:8088.** 

Nell' IDP metadata   ho come partner name e come provider ID http://0.0.0.0:8088/, e come BIND POST e redirect http://0.0.0.0:8088/sso. Da dove prende l'IDP  il valore destination? come fare a modificarlo eventualmente?
Inotre mi torna il seguente errore:

**xpath: {urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest/{urn:oasis:names:tc:SAML:2.0:protocol}NameIDPolicy - attribute: SPNameQualifier https://_xxx.yyy.zzz_/isam/sps/SPIDSP/saml20 extra keys not allowed**
 
è normale  rispetto alle specicfiche AGID che non deve essere presente tale attributo nell'elemento NameIDPolicy?

**Comment by alranel** [comment]
Riguardo alle due domande:

1. Le regole tecniche SPID prescrivono, contrariamente allo standard SAML, che nell'attributo `Destination` sia presente l'entityID dell'Identity Provider anziché l'URL dell'endpoint di destinazione. L'errore rilevato è pertanto corretto.
2. L'attributo `SPNameQualifier` non è proibito dalle regole SPID, per cui la più recente versione del testenv2 non rileva errori in caso di sua presenza.

**Comment by stefanococco** [comment]
> 
> 
> Riguardo alle due domande:
> 
>     1. Le regole tecniche SPID prescrivono, contrariamente allo standard SAML, che nell'attributo `Destination` sia presente l'entityID dell'Identity Provider anziché l'URL dell'endpoint di destinazione. L'errore rilevato è pertanto corretto.
> 
>     2. L'attributo `SPNameQualifier` non è proibito dalle regole SPID, per cui la più recente versione del testenv2 non rileva errori in caso di sua presenza.

Salve, io sto usando l'ultima versione di italia/spid-testenv2 presente su Docker Hub e l'attributo "SPNameQualifier" mi viene segnalato come "item not allowed" ed "NameQualifier" come richiesto e non fornito.
