### ISSUE TITLE
Bug: il caricamento dei metadati viene interrotto se un file di metadati non passa la validazione

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#210]
Se ho più metadati SP configurati, ed uno fallisce la validazione (quindi con errori di validazione scritti a console durante l'avvio del testenv), i successivi non vengono né caricati né validati.

Il testenv dovrebbe provare a caricare tutti i metadati configurati, saltando solo quelli non validi.

**Comment by bfabio** [comment]
Reopening after the revert in #320.

**Comment by peppelinux** [comment]
risolto qui
https://github.com/italia/spid-testenv2/blob/master/testenv/utils.py#L90
