### ISSUE TITLE
Invalid Response

### ISSUE THREAD

**Issue by fauriemma** [italia/spid-testenv2#213]
Stiamo testando un nuovo SP tramite https://idp.spid.gov.it ma otteniamo sempre il seguente errore AttrChecker

The response obtained from the Identity Provider is not valid. Please check the returned authnContextClassRef and/or the returned attributes.

Controllando request e response riscontriamo che se pur nella request ci sia 

<saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL2</saml:AuthnContextClassRef>

nella response otteniamo 

<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml2:AuthnContextClassRef>

questo comporta che la validazione fallisce e la sessione viene annullata.

Potreste darci qualche dritta?

[request.log](https://github.com/italia/spid-testenv2/files/2838636/request.log)
[response.log](https://github.com/italia/spid-testenv2/files/2838637/response.log)

**Comment by alranel** [comment]
Buongiorno, vi consigliamo di usare l'IdP di test contenuto nel presente repository.
idp.spid.gov.it è un ambiente deprecato.
