### ISSUE TITLE
TestEnv2 - Metadato idp non caricato

### ISSUE THREAD

**Issue by rmonacoAPS** [italia/spid-testenv2#214]
Ho installato spid-testenv2, configurato ed avviato con python spid-testenv.py
Quando tento di avviare SP Shibboleth, il metadato dell'idp non viene caricato, restituendo il seguente messaggio di errore:

2019-02-11 16:51:01 INFO OpenSAML.MetadataProvider : applying metadata filter (Signature)
2019-02-11 16:51:01 ERROR XMLTooling.ParserPool [http://10.253.0.140:8088]: error on line 46, column 25, message: element 'SingleLogoutService' is not allowed for content model '(Signature?,Extensions?,KeyDescriptor*,Organization?,ContactPerson*,ArtifactResolutionService*,SingleLogoutService*,ManageNameIDService*,NameIDFormat*,SingleSignOnService+,NameIDMappingService*,AssertionIDRequestService*,AttributeProfile*,Attribute*)'
2019-02-11 16:51:01 ERROR OpenSAML.MetadataProvider.XML [http://10.253.0.140:8088]: error while loading resource (/opt/shibboleth/metadata/idp.spid.gov.it.xml): XML error(s) during parsing, check log for specifics.

Di seguito il file sp_metadata.xml

[sp_metadata.txt](https://github.com/italia/spid-testenv2/files/2854897/sp_metadata.txt)

Qualcuno può aiutarmi?

Grazie in anticipo.

**Comment by alranel** [comment]
C'era un errore nei metadati IdP generati dal testenv. @rmonacoAPS, con la correzione che ho apportato funziona?

**Comment by rmonacoAPS** [comment]
Buonasera, in realtà nel frattempo siamo andati avanti senza spid-test-env per l'implementazione di spid.
Attualmente però dopo aver implementato tutta la parte di autenticazione con SP Shibboleth, risulta che  il servizio, implementato per la Città Metropolitana di Napoli, non presenta il comportamento previsto come illustrato nel documento SPID Quality Assessment Document.  

Nel dettaglio nel report sulla conformità Tecnica, risulta che il servizio accetta le response (errate) con i seguenti parametri, invece di rifiutarle:
17. Response - InResponseTo mancante
18. Response - InResponseTo diverso da Request
43. Assertion - Elemento NameID non specificato
44. Assertion - Elemento NameID mancante
45. Assertion - Attributo Format di NameID non specificato
46. Assertion - Attributo Format di NameID mancante
47. Assertion - Attributo Format di NameID diverso
48. Assertion - Attributo NameQualifier di NameID non specificato
49. Assertion - Attributo NameQualifier di NameID mancante
50. Assertion - NameQualifier di NameID diverso da EntityID del S.P.
51. Assertion - Elemento SubjectConfirmation non specificato
61. Assertion - Attributo InResponseTo di SubjectConfirmationData mancante
62. Assertion - Attributo InResponseTo di SubjectConfirmationData diverso da ID request
70. Assertion - Attributo Format di Issuer non specificato
71. Assertion - Attributo Format di Issuer mancante
73. Assertion - Elemento Conditions non specificato
74. Assertion - Elemento Conditions mancante
76. Assertion - Attributo NotBefore di Condition mancante
80. Assertion - Attributo NotOnOrAfter di Condition mancante
84. Assertion - Elemento AudienceRestriction di Condition mancante
94. Assertion - Elemento AuthContextClassRef impostato su https://www.spid.gov.it/SpidL1
95. Assertion - Elemento AuthContextClassRef impostato su https://www.spid.gov.it/SpidL2
96. Assertion - Elemento AuthContextClassRef impostato su https://www.spid.gov.it/SpidL3
97. Assertion - Elemento AuthContextClassRef impostato ad un valore non previsto
99. Assertion - Elemento AttributeStatement presente, con sottoelemento Attribute non specificato
103. Assertion - Set di attributi inviato diverso da quello richiesto
104. Anomalie utente - Ripetuta sottomissione di credenziali errate (Anomalia 19)
105. Anomalie utente - Utente privo di credenziali compatibili (Anomalia 20)
106. Anomalie utente - Timeout (Anomalia 21)
107. Anomalie utente - Consenso negato (Anomalia 22)
108. Anomalie utente - Credenziali bloccate (Anomalia 23)


Qualcuno può aiutarmi a risolverli?

Occorre settare/modificare parametri lato SP Shibboleth? Oppure occorre implementare controlli proprietari lato applicativo?

Vi ringrazio anticipatamente.

Saluti.

**Comment by Eduardo1977** [comment]
Buongiorno, anche noi dovremmo risolvere gli stessi problemi per la nostra implementazione.
Avreste qualche indicazione utile? Bisogna agire su qualche configurazione di SP Shibboleth?
