### ISSUE TITLE
AuthnRequest attribute: Destination

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-testenv2#217]
Sto implementando un SP al di sopra di pysaml2, ho patchato la produzione automatica dei metadati lato SP per le validazioni SPID ma in fase di AuthnRequest l'idp spid-testenv2 riporta:

````
AuthnRequest attribute: Destination

il valore dell'elemento è diverso da quello atteso:
(http://idpspid.testunical.it:8088)

http://idpspid.testunical.it:8088/sso
````

Ho patchato il mio SP, forzando come destination (location in pysaml2) il fqdn dell'IDP, ottenendo quindi come segue:
````
<ns0:AuthnRequest 
  AssertionConsumerServiceURL="http://sp1.testunical.it:8000/saml2/acs/" 
  Destination="http://idpspid.testunical.it:8088" 
  ForceAuthn="true" 
  ID="id-P5lUodVhrIjDvi0rU" 
  IssueInstant="2019-04-01T12:37:49Z" 
  ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" 
  Version="2.0" xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" 
  xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion"
  xmlns:ns2="http://www.w3.org/2000/09/xmldsig#">
````

Credo che questo aspetto potrebbe essere valutato come "design implementation error" dato che l'endpoint del sso, la destinazione lato idp, è appunto `http://idpspid.testunical.it:8088/sso` e non `http://idpspid.testunical.it:8088`.

**Comment by AntonioGiovanniSchiavone** [comment]
Come indicato sul [sito ufficiale SPID](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid), la documentazione tecnica è composta dalle [Regole recanti le norme tecniche SPID](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf), gli [AVVISI SPID](https://www.agid.gov.it/it/piattaforme/spid/avvisi-spid), la [Tabella delle Anomalie SPID](https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/spid-messaggi.pdf) e le [Linee Guida sulle Interfacce](https://www.spid.gov.it/assets/res/agid-spid-lg-interfacce-informazioni-idp-sp.pdf).

A pag. 8 le Regole recanti le norme tecniche SPID definiscono che l'attributo Destination deve essere valorizzato con l'entityID dell'Identity Provider. Recentemente l'Avviso SPID n° 11 ha esteso la valorizzazione anche all' SSO dell'Identity Provider

**Comment by peppelinux** [comment]
Grazie infinite, ti sono veramente grato. Potremmo quindi implementare in spid-testenv2 l'indicazione riportata nell'avviso num11.

Questo mi consentirebbe di non specializzare l'argomento destination nel metodo authn request. Che ne pensi?

**Comment by alranel** [comment]
Sì, si dovrebbero aggiornare sia le regole tecniche consolidate sia questo IdP di test sulla base di quell'avviso 11 (che ignoravo)
