### ISSUE TITLE
AuthnRequest/NameIDPolicy - attribute: AllowCreate: item not allowed

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-testenv2#218]
spid-testenv2 riporta che l'AuthnRequest non dovrebbe avere NameIDPolicy.AllowCreate valorizzato, sia esso True o False. Questo invece parrebbe in contraddizione con le [Regole tecniche v1](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf) che riporta che se valorizzato dovrebbe essere True.

Il mio SP pysaml2 di default produce le AuthnRequest con questa NameIDPolicy
````
<ns0:NameIDPolicy AllowCreate="false"
  Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
````

Ho apposto una patch per rimuovere questo attributo da NameIDPolicy. Vorrei pertanto chiedere in questa Issue di rivedere questo aspetto per una maggiore conformità allo standard OASIS, che [qui](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) riporta che se AllowCreate mancasse assumerebbe come valore default False, pertanto se fosse specificato perché non consentirlo?

**Comment by AntonioGiovanniSchiavone** [comment]
Come indicato sul [sito ufficiale SPID](https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid), la documentazione tecnica è composta dalle [Regole recanti le norme tecniche SPID](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf), gli [AVVISI SPID](https://www.agid.gov.it/it/piattaforme/spid/avvisi-spid), la [Tabella delle Anomalie SPID](https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/spid-messaggi.pdf) e le [Linee Guida sulle Interfacce](https://www.spid.gov.it/assets/res/agid-spid-lg-interfacce-informazioni-idp-sp.pdf).

In particolare, l'Avviso SPID n°5 ha rimosso l'indicazione dell'attributo AllowCreate.

**Comment by peppelinux** [comment]
Ciao Antonio, grazie per la risposta e per i dettagli. Probabilmente la rimozione della documentazione datata potrebbe aiutarci a rimuovere dubbi di questo tipo, questa ad oggi risulta essere indicizzata benissimo sui motori di ricerca. La documentazione che mi indichi è oltremodo chiara, ho aperto questa issue per porre l'attenzione sulla possibilitá di conformare ulteriormente SPID allo standard OASIS senza alcun sconvolgimento dell'assetto attuale. 

La possibilitá che SPID si adegui ad uno standard globalmente riconosciuto risulterebbe vantaggioso. AllowCreate se presente dovrebbe essere false, se assente sarebbe false di default. Questo è lo standard, ho dovuto personalizzare l'implementazione authnrequest di pySAML2 come workaround, potremmo generalizzare meglio lattuale implementazione delle regole tecniche senza rinunciare alla sicurezza o alla continuitá di servizio. Che ne pensi?

Piú che una idea per il presente questo sarebbe un pensiero per il presente futuro 😎

**Comment by alranel** [comment]
Le regole tecniche consolidate sono il documento di più facile consultazione poiché contengono già gli avvisi applicati:
https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/
