### ISSUE TITLE
Interfacce aggiornate

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#22]
Qui si trovano per ora i mockup delle interfacce SPID aggiornate:

~https://github.com/vito80ba/spid-idp-login-layout/tree/redesign~

**Comment by alexrj** [comment]
I file sono stati spostati qui nel repository ufficiale:

https://github.com/italia/spid-idp-login-layout/tree/new-ux-guidelines

**Comment by alexrj** [comment]
Poco fa è stato fatto il push con una ulteriore revisione di quelle interfacce.

**Comment by fmarco** [comment]
@alexrj ottimo, grazie.

**Comment by alexrj** [comment]
Usando l'attuale master, se all'atto del login inserisco credenziali sbagliate ottengo una brutta pagina "403 Forbidden". Anche in quel caso bisogna usare la grafica aggiornata, con un messaggio e un'esperienza analoga a quanto avviene negli IdP reali.

**Comment by alexrj** [comment]
Il logo SPID in alto a sinistra previsto dal mockup ha accanto un numerino cerchiato. Quel numerino deve cambiare a seconda del livello SPID con cui si sta entrando (1, 2, 3). Adesso invece in testenv2 è sempre 3 a prescindere dal livello.

**Comment by alexrj** [comment]
Ho testato il branch `feature/issue-3-validazione-login`.

Se all'atto del login inserisco credenziali sbagliate ottengo il messaggio "Accesso non consentito". Bisogna usare il template `index-error.html` presente nel repository linkato sopra.

**Comment by fmarco** [comment]
@alexrj questa issue è ancora valida?

**Comment by alexrj** [comment]
Sì @fmarco, manca questa cosa:

> Il logo SPID in alto a sinistra previsto dal mockup ha accanto un numerino cerchiato. Quel numerino deve cambiare a seconda del livello SPID con cui si sta entrando (1, 2, 3). Adesso invece in testenv2 è sempre 3 a prescindere dal livello.

**Comment by alranel** [comment]
Fatto
