### ISSUE TITLE
Verifica obbligatorietà RequestedAttribute

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-testenv2#224]
Nei metadati SP, se l'AttributeConsumingService non contiene alcun RequestedAttribute, l'ambiente docker avvia il portale ma i tentativi di SSO falliscono con un errore non parlante (AttributeError: 'ServiceProviderMetadata' object has no attribute 'decode'). Sarebbe meglio se il docker rifiutasse l'avvio e generasse qualche errore specifico nei logs.

Esempio di metadato: [sp_metadata.txt](https://github.com/italia/spid-testenv2/files/3124081/sp_metadata.txt)

**Comment by peppelinux** [comment]
Se l'eccezzione avviene in testenv.server.handle_error questa è probabilmente riconducibile qui:
https://github.com/italia/spid-testenv2/issues/237

prego pubblicare screenshot o traceback dell'eccezione per avere conferma.

**Comment by lscorcia** [comment]
Uhm, purtroppo questa si verifica ancora, sebbene l'errore sia cambiato, non è comunque molto parlante: il server non si avvia e nei logs di docker trovo solo:

DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary

Ad ogni modo è un problema così scemo che non c'è problema se la issue la si chiude e basta, nessuno dovrebbe creare AttributeConsumingService senza nemmeno un attributo :)
