### ISSUE TITLE
Verifica obbligatorietà ServiceName/ServiceDescription

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-testenv2#225]
Nei metadati SP, se l'AttributeConsumingService non contiene i valori di ServiceName/ServiceDescription, o se questi sono presenti ma vuoti, l'ambiente docker avvia il portale ma i tentativi di SSO falliscono con un errore non parlante (AttributeError: 'ServiceProviderMetadata' object has no attribute 'decode'). Sarebbe meglio se il docker rifiutasse l'avvio e generasse qualche errore specifico nei logs.

Esempio di metadato: [sp_metadata.txt](https://github.com/italia/spid-testenv2/files/3124087/sp_metadata.txt)

**Comment by peppelinux** [comment]
Se l'eccezzione avviene in testenv.server.handle_error questa è probabilmente riconducibile qui:
https://github.com/italia/spid-testenv2/issues/237

prego pubblicare screenshot o traceback dell'eccezione per avere conferma.

**Comment by peppelinux** [comment]
Risolto qui:
https://github.com/italia/spid-testenv2/issues/237

@lscorcia la chiudiamo questa?

**Comment by lscorcia** [comment]
Confermo, l'errore non si verifica più su versione corrente. Grazie!
