### ISSUE TITLE
Request Logout e attributo Destination

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-testenv2#226]
Nel corso dell'ultimo commit per fixare #221, probabilmente è scappato un typo importante alla riga https://github.com/italia/spid-testenv2/blob/5583893191e885337f3a6425e5faed77f41949e7/testenv/validators.py#L734 
che dovrebbe essere

`[entity_id, self._config.absolute_slo_url], `

altrimenti non la validazione continua a bloccare l'endpoint di Logout dichiarato nei metadata.

Grazie e buona serata

**Comment by alranel** [comment]
Grazie per la segnalazione! Ho corretto il typo.
