### ISSUE TITLE
Metadata IDP - è corretto esporre gli endpoint http-redirect?

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-testenv2#227]
Nel testenv2, il metadato esposto dall'IDP (http://localhost:8088/metadata) riporta gli endpoint sia in http-post sia in http-redirect, ma se non erro la specifica SPID prevede esclusivamente http-post.

E' intenzionale l'esposizione di http-redirect?
Grazie e buona giornata

**Comment by alranel** [comment]
Le regole tecniche SPID ammettono sia HTTP-POST sia HTTP-Redirect:
https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/metadata.html#identity-provider
