### ISSUE TITLE
Authentication via endpoint HTTP-Redirect

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-testenv2#228]
Appurato che spid-testenv supporta anche il binding HTTP-Redirect in aggiunta a HTTP-Post, non capisco perché l'ambiente mi restituisce errore durante una chiamata che utilizza questo binding.

Request:
```
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="idc1501356ab894e0aa5bc308c4219532b" Version="2.0" IssueInstant="2019-05-01T15:44:05Z" Destination="http://192.168.99.100:8088/sso" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" AssertionConsumerServiceURL="http://localhost:17009/SamplePath/Saml2/Acs" AttributeConsumingServiceIndex="0">
  <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="http://localhost:17009/SamplePath/Saml2">http://localhost:17009/SamplePath/Saml2</saml2:Issuer>
  <saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
  <saml2p:RequestedAuthnContext Comparison="exact">
    <saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef>
  </saml2p:RequestedAuthnContext>
</saml2p:AuthnRequest>
```

Response:
`AuthnRequest - attribute: ProtocolBinding`
`Il valore dell'elemento è diverso dal valore atteso (urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST):urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect`

Grazie per l'aiuto

**Comment by fmarco** [comment]
@lscorcia ciao, per quanto riguarda l'attributo `ProtocolBinding`  relativo alla `AuthnRequest` si tratta del  binding da utilizzare per inoltrare il messaggio di risposta, vedi https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html#authnrequest .

**Comment by lscorcia** [comment]
Grazie mille per la spiegazione, ho fatto confusione io.
Buona serata
