### ISSUE TITLE
spid-testenv2  e  spid-sp-shibboleth

### ISSUE THREAD

**Issue by AlbertoDalmaso** [italia/spid-testenv2#230]
Buon giorno,
ho installato il docker di spid-testenv2 (scaricando il container tramite le funzioni di docker, non compilandolo in locale) e sto provando a connettere un client apache/shibboleth.
dopo aver configurato il file dei metadati sul docker, ho scaricato la configurazione lato client dal  progetto italia/spid-sp-shibboleth, personalizzato il file di configurazione affinché veda il server IdP e provato ad eseguire il login.
Effettivamente, partendo dal SP, viene caricata la pagina dell'IdP, ma con un laconico
"Dato mancante nella request: 'SigAlg'"
Come posso intervenire per ovviare a questo errore e continuare i test?
Grazie per l'attenzione e per il lavoro che fate!

**Comment by peppelinux** [comment]
un SP SPID richiede sia sia i metadata che le AuthnRequest vengano fatte in stretta osservanza alle regole tecniche SPID.
Su developers italia ci sono alcuni progetti di SP SPID realizzati con shibboleth, sono sicuro che li troverai gli esempi che cerchi
