### ISSUE TITLE
Dato mancante nella request: 'SAMLRequest'

### ISSUE THREAD

**Issue by umigliore** [italia/spid-testenv2#234]
Stiamo utilizzando la libreria spid-php-lib che funziona bene con il sito di test idp.spid.gov.it
Invece su spid-testenv2 la risposta è sempre "Dato mancante nella request: 'SAMLRequest'", sia provando l'HTTP Redirect che l'HTTP Post.
Tracciando su browser le chiamate il messaggio sembra completo, sicuramente la chiave viene passata:
http://xxxxxxxxx/login?SAMLRequest=...

**Comment by alessandroponzo** [comment]
Riscontro lo stesso problema

**Comment by umigliore** [comment]
Risolto, riporto qua la soluzione :
 nel config.yaml per l'endpoints _single_sign_on_service_ non va usato "login" che va in conflitto con un login già presente nella route dal server; l'esempio proposto "/sso" funziona.
