### ISSUE TITLE
AuthnRequest/NameIDPolicy - attribute: AllowCreate	- item not allowed

### ISSUE THREAD

**Issue by gianpaolot** [italia/spid-testenv2#235]
Buongiorno,
faccio riferimento alle segnalazione  #218. Sto provando a fare i test indicati utilizzando il progetto spid-testenv2. Come componente per l'integrazione sto usando SPID Auth Docker nella versione 0.

provando a fare la chiamata all'idp di test locale generato con spid-testenv2 mi ritorna l'errore:

> 
AuthnRequest/NameIDPolicy - attribute: AllowCreate 

<samlp:NameIDPolicy AllowCreate="1" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/

> 

nella issues #218 viene riportato che nella documentazione è stata rimossa l'indicazione  dell'attributo AllowCreate. Volevo chiedervi se potevate darmi  indicazioni su come rimuovere questo errore per continuare i test.

Grazie

**Comment by pladgepeople** [comment]
Quoto

**Comment by peppelinux** [comment]
Attualmente l'unica soluzione è quella di rimuovere allowcreate, anche a me sarebbe piaciuto settarlo a false soltanto.

**Comment by peppelinux** [comment]
Basta rimuovere l'attributo, anche se è assurdo doverlo fare, questo attributo se valorizzato a False dovrebbe idealmente funzionare esattamente come se fosse stato rimosso ...

ma così è SPID
https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid-avviso-n5-regole-tecniche-errata-corrige.pdf
