### ISSUE TITLE
Spid Ambiente di Test online

### ISSUE THREAD

**Issue by lespaul121** [italia/spid-testenv2#236]
Salve,

fino ha qualche giorno fa, utilizzavo l'ambiente di test online https://idp.spid.gov.it/.
Avevo resgistrato il mio Service Provider e tutto funzionava correttamente.
Purtroppo adesso è stato cambiato tutto. Allo stesso indirizzo è possibile
scaricare l' EntityDescriptor dell' Identity Provider ma non è possibile registrare il mio
ServiceProvider.

Qualcuno può darmi qualche indicazione utile?
Non riesco a trovare informazioni a riguardo.

Grazie in anticipo

Ciao

**Comment by damikael** [comment]
Salve,

è possibile registrare il proprio metadata sull'idp di test all'indirizzo https://idp.spid.gov.it/admin/databasesprecord/

(Rif. https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid#procedura-tecnica-4)
