### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by damikael** [italia/spid-testenv2#237]
Spesso, all'arrivo di AuthnRequest, il server ritorna il seguente errore:

`AttributeError: 'str' object has no attribute 'decode'` (vedi immagine allegata)

entrando in uno stato di eccezione permanente per cui tutte le successive richieste riscontrano lo stesso errore e non risulta più possibile utilizzare l'ambiente.

Non è chiaro se la causa è da ricercare in una sintassi malformata della Request, che sembra essere invece corretta. La stessa Request, infatti, in altre occasione non causa l'errore.
Riavvio del server risolve il problema.

<img width="472" alt="error_testenv2" src="https://user-images.githubusercontent.com/31276401/64604402-5eda6d00-d3c2-11e9-8557-c9da7c02152c.PNG">

**Comment by pladgepeople** [comment]
riscontriamo lo stesso errore e purtroppo non riusciamo più a fare le richieste:

builtins.AttributeError

AttributeError: 'str' object has no attribute 'decode'

![Schermata 2019-10-02 alle 22 02 41](https://user-images.githubusercontent.com/39263226/66146301-ca53db00-e60c-11e9-91d0-fa6d61193f4f.png)

**Comment by peppelinux** [comment]
@damikael ciao, questo genere di errore è stato riscontrato per un periodo di tempo anche su altre piattaforme sai... Come se ad un tratto alcune implementazioni di Flask/wsgi ottenessero le request come byte e non piú come str.

Ancora non ho testato ma se possibile provare a fare un upgrade di tutte le librerie prima di applicare ulteriori patch ed analisi

**Comment by peppelinux** [comment]
cmq una patch potrebbe essere semplice, qui https://github.com/italia/spid-testenv2/blob/master/testenv/server.py#L216 basterebbe modificare come segue

````
    def _handle_errors(self, xmlstr, errors=None):
        xmlstr = xmlstr if isinstance(xmlstr, str) else xmlstr.decode("utf-8")
        rendered_error_response = render_template(
            'spid_error.html',
            **{
                'lines': xmlstr.splitlines(),
                'errors': errors
            }
        )
        return rendered_error_response
````

**Comment by damikael** [comment]
@peppelinux grazie per il contributo. Potresti proporre una pull request per la patch?

**Comment by pladgepeople** [comment]
@peppelinux grazie per la patch.. noi purtroppo stiamo testando direttamente sull'idp test  https://idptest.spid.gov.it/sso senza passare dal spid-testenv2 e l'errore lo otteniamo on line quindi non possiamo agire direttamente sul sito test forse per questo può tornare utile @damikael ?

**Comment by damikael** [comment]
@pladgepeople l'idp di test online è collegato a dockerhub. Quando la patch sarà pubblicata l'aggiornamento si potrà riflettere online

**Comment by peppelinux** [comment]
eccola
https://github.com/italia/spid-testenv2/pull/243
