### ISSUE TITLE
Installazione non riuscita

### ISSUE THREAD

**Issue by litesdeveloper** [italia/spid-testenv2#238]
L'ambiente non funziona.
Quando si installa ( con Docker ) : 

> /usr/local/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:Impossibile accedere al file di configurazione: ./conf/config.yaml
/usr/local/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:Impossibile accedere al file di configurazione: ./conf/config.yaml
/usr/local/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:Impossibile accedere al file di configurazione: ./conf/config.yaml
/usr/local/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:Impossibile accedere al file di configurazione: ./conf/config.yaml

**Comment by bfabio** [comment]
That's because the initial [configuration](https://github.com/italia/spid-testenv2#configurazione) is not automatically carried out for you when the container is started. It probably should be.
