### ISSUE TITLE
Errore in autenticazione con IDP di test

### ISSUE THREAD

**Issue by pladgepeople** [italia/spid-testenv2#242]
errore noto e comune:

![Schermata 2019-10-02 alle 22 02 41](https://user-images.githubusercontent.com/39263226/66146357-e9526d00-e60c-11e9-873c-225245e4a815.png)

**Comment by peppelinux** [comment]
fixato qui: https://github.com/italia/spid-testenv2/pull/243
puoi chiudere questa issues appena reiteri il tuo test

**Comment by pladgepeople** [comment]
certo appena è risolto chiudo

**Comment by damikael** [comment]
Vi farò sapere quando l'immagine compilata sarà disponibile su dockerhub e l'ambiente online aggiornato, così da poter rieseguire il test.

**Comment by damikael** [comment]
@alranel attendo tuo feedback in merito alla disponibilità della nuova immagine su dockerhub per aggiornare l'ambiente online.

**Comment by peppelinux** [comment]
Pensavo fosse automatico tramite bot
https://docs.docker.com/docker-hub/builds/link-source/

Piuttosto @alranel lo testa e lo pubblica su dockerhub mi sembra di capire

**Comment by pladgepeople** [comment]
@alranel attendiamo te.... oggi ho ancora lo stesso problema 
@peppelinux si anche io pensavo fosse automatico
@damikael grazie del supporto

**Comment by damikael** [comment]
L'ambiente di test online è aggiornato
