### ISSUE TITLE
Documentare le API con Swagger

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#25]
https://swagger.io sembra essere popolare per documentare / rendere testabili / usabili le API, potrebbe essere utile supportarlo ?

**Comment by fmarco** [comment]
@simevo in questa fase probabilmente non è necessario, ma se le API dovessero espandersi potrebbe aver senso una soluzione del genere.

**Comment by alexrj** [comment]
Sì, certo, Swagger è una soluzione popolare per documentarle. Per essere chiari, le uniche API che il testenv2 esporrà saranno quelle per poterlo pilotare da un sistema esterno (come quello di onboarding di AgID), e non saranno necessarie per usarlo in modalità standalone.

**Comment by alranel** [comment]
Ad oggi si è scelto di non sviluppare API ma di usare un database PostgreSQL che gli applicativi esterni possono leggere/scrivere direttamente.
