### ISSUE TITLE
spid-testenv2 problemi caricamento metadata SP come URL risolvibili con patch

### ISSUE THREAD

**Issue by guidross** [italia/spid-testenv2#257]
Martedì abbiamo installato spid-testenv2 su un nostro server ma avevamo incontrato difficoltà a farlo partire: analizzando il problema abbiamo trovato la soluzione descritta sotto come spunto per sistemare il codice e avere una soluzione funzionante.

Avevamo configurato il file conf/config.yaml con gli url dei metadata nella sezione "remote:" inq questo modo:

   remote:
       - "https://www.example1.com/metadata.xml"
       - "https://www.example2.com/metadata.xml"

Lanciando l'IdP di test tuttavia compariva il seguente errore:

ERROR:testenv.log:expected a dictionary @ data['metadata']['remote'][0]

Infatti, da un controllo del codice (file /opt/SPID/spid-testenv2/testenv/config.py, function __init_schema__), per la sezione "remote:" risulta essere obbligatorio indicare un dictionary per ogni metadata avente una chiave "url" e valore l'url del metadata e un eventuale chiave "cert" non descritta, ma immagino per caricare un certificato.

Ho proceduto con la correzione del file conf/config.yaml così:

   remote:
       - url: "https://www.example1.com/metadata.xml"
       - url: "https://www.example2.com/metadata.xml"

e l'errore iniziale era sparito, ma se ne era presentato un altro:

testenv.exceptions.MetadataLoadError: La richiesta all'endpoint HTTP '{'url': 'https://www.example1.com/metadata.xml'}': 'No connection adapters were found for '{'url': 'https://www.example1/metadata.xml'}''

Approfondendo è emerso che il codice di caricamento dei metadata come url si aspetta proprio un url mentre riceve un dictionary.

Nella versione attualmente pubblicata c'è quindi una incongruenza tra il parser dello schema del file di configurazione e il codice caricamento metadata: il parser richiede un dictionary mentre il codice si aspetta un url.

Ho risolto il problema modificando il codice del costructor della classe ServiceProviderMetadataHTTPLoader nel file /opt/SPID/spid-testenv2/testenv/spmetadata.py che allego: così funziona.

Inoltre, al lancio dell'IdP SPID, compariva la warning

/opt/SPID/spid-testenv2/testenv/config.py:296: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

Nella pagina web citata c'è la soluzione per togliere tale messaggio: si tratta di utilizzare la funzione yaml.full_load() che impedisce l'interpretazione del parametro come codice eseguibile (!!) anziché yaml.load().

**Comment by bfabio** [comment]
Hi @guidross, I have a patch in store for that `yaml.load()` issue.

About the format of `remote:`: it looks like the value in `"cert"` is never used in the code, so I'm wondering if that's just a leftover from a feature that was never really supported.

Maybe @sanjioh (hi), who seems the author of that portion, can help us clarify the situation.

**Comment by bfabio** [comment]
Duplicate of #229
