### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#26]
Bisogna creare un'immagine Docker, collegata via CI con questo repository, per facilitare l'installazione.

**Comment by simevo** [comment]
docker è un sistema per gestire container abbastanza opinionato, ne esistono tanti altri (systemd nspawn per i temerari, io uso uso lxc sul ns cloud privato, c'è lxd, kubernetes ...)

il configuration management invece permette di creare delle ricette astratte che poi possono andare sul ferro, su VM indipendenti o su container (anche docker)
noi usiamo ansible, quindi ho creato #29

ma una cosa non esclude l'altra !  chissà se l'immagine docker potrebbe essere basata su ansible ? non sono abbastanza ferrato su docker per rispondere ...

**Comment by fmarco** [comment]
@alexrj aggiunto Dockerfile

**Comment by fmarco** [comment]
@alexrj questa direi che si può chiudere
