### ISSUE TITLE
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']

### ISSUE THREAD

**Issue by ivancarlucci** [italia/spid-testenv2#261]
Salve a tutti, ho questo errore. Sto usando docker, ho configurato il metadata nel config.yaml, mi sembra tutto corretto. Potete aiutarmi? Grazie in anticipo

_Originally posted by @ivancarlucci in https://github.com/italia/spid-testenv2/issues/212#issuecomment-548276128_

**Comment by bfabio** [comment]
Ciao, puoi incollare il tuo `config.yaml`?

**Comment by ivancarlucci** [comment]
[config.zip](https://github.com/italia/spid-testenv2/files/3793099/config.zip)

**Comment by bfabio** [comment]
@ivancarlucci Il file sembra a posto, ho provato a fare partire un container.

Sei sicuro di sare usando quel file?

Qual è l'output di (sostituisci "`/etc/spid-testenv2`" con la directory in cui hai il file di configurazione)
```
docker run -p 8088:8088 --mount src="/etc/spid-testenv2",target="/app/conf",type=bind  italia/spid-testenv2
```

**Comment by ivancarlucci** [comment]
In effetti ho questo errore abbastanza eloquente:
testenv.exceptions.MetadataLoadError: Impossibile leggere il file './conf/sp_metadata.xml': '[Errno 2] No such file or directory: './conf/sp_metadata.xml''
Però il file è presente nella directory di destinazione...forse deve essere presente anche in quella di origine?

**Comment by bfabio** [comment]
Con quella configurazione, `sp_metadata.xml` deve essere nella stessa directory di `config.yaml`.

Nota a margine: è controintuitivo, perché quel `./conf` parte dalla root dell'applicazione, invece di partire dalla directory in cui c'è `config.yaml`. Magari apro un baco per quello.

**Comment by ivancarlucci** [comment]
Sì, comunque è presente nella stessa directory di config.yaml

**Comment by bfabio** [comment]
```docker run --entrypoint /bin/bash --volume "/etc/spid-testenv2:/app/conf" italia/spid-testenv2 -c "(ls -l conf ; pwd)"```

cosa dice?

**Comment by bfabio** [comment]
@ivancarlucci Hai novità?

**Comment by ivancarlucci** [comment]
Sì scusami se non ho più risposto. Alla fine non ho risolto e quello che ho fatto è stato ripercorrere tutti i passi dell'installazione e rifare il container. In questo modo ha funzionato tutto.

**Comment by publicocean0** [comment]
il docker sembra non aggiornato, presenta lo stesso errore

**Comment by Borman95** [comment]
Buongiorno volevo segnalare che anche a me compare lo stesso errore.
Alla fine è stato risolto? se si, come?

**Comment by gmstyle** [comment]
stesso problema anche io con container. Va in restarting

root@gtv-HP-Notebook:/etc/spid-testenv2# docker logs -f spid-testenv2
Generating conf/idp.key and conf/idp.crt...
Generating a RSA private key
...............................................................................................................................................+++++
....+++++
writing new private key to 'conf/idp.key'
-----
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']
root@gtv-HP-Notebook:/etc/spid-testenv2# 

e questo è il risultato di:

root@gtv-HP-Notebook:/etc/spid-testenv2# docker run -p 8088:8088 --mount src="/etc/spid-testenv2",target="/app/conf",type=bind  italia/spid-testenv2
DEBUG:faker.factory:Not in REPL -> leaving logger event level as is.
ERROR:testenv.log:expected a dictionary for dictionary value @ data['metadata']

**Comment by gmstyle** [comment]
io ho risolto decommentando le righe seguenti

local:
     - "./conf/sp_metadata.xml"

nella sezione CONFIGURAZIONE SERVICE PROVIDER del file config.yaml

**Comment by Borman95** [comment]
Grazie.
Ho risolto anche io alla stessa maniera.
