### ISSUE TITLE
BUG: Il server non accetta più SAMLRequest se un metadato fallisce la validazione

### ISSUE THREAD

**Issue by nataz77** [italia/spid-testenv2#262]
Salve, abbiamo installato localmente l'IDP, seguendo passo per passo la guida di installazione.
Abbiamo notato, sia nell'ambiente locale che su quello disponibile presso [idptest.spid.gov.it ](idptest.spid.gov.it) che se viene caricato un metadata invalido, il server risponde sempre con la pagina di errore di validazione a qualsiasi SAMLRequest provienente da un qualsiasi SP censito e non da quello con il metadata invalido (cioè anche se ho un metadato valido vedo la pagina di errore dell'SP che ha provocato l'errore).
Un workaround consiste nel riavviare il container dell'IDP, ma se si prova ad accedere tramite l'SP che ha il metadato invalido il problema si ripresenta.
Sembra un bug simile al #210, ma in questo caso piuttosto che interrompere il caricamento dei metadati il server risponde con la pagina di errore di validazione a qualsiasi tentativo di accesso.

**Comment by peppelinux** [comment]
questo problema è stato risolto patchando il meccanismo di caricamento dei metadata

in particolare
https://github.com/italia/spid-testenv2/blob/a1adb759bd2bede102be2bcbffc8fe346a6586b0/testenv/utils.py#L90
