### ISSUE TITLE
Generazione metadata SP

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#28]
Ad oggi si può usare l'interfaccia del vecchio sistema di test: https://idp.spid.gov.it:8080/

Potremmo:

1. fornire un metadata di esempio nel repository, con i commenti che guidano l'utente nella sua compilazione
2. fornire anche qui un'interfaccia web per la compilazione guidata

L'interfaccia in questione sarebbe in parte condivisa con quella necessaria per lo scenario n. 2 descritto in #19.

**Comment by fmarco** [comment]
@alexrj si potrebbe aggiungere un endpoint per la generazione del metadata, forse è la strada più comoda

**Comment by fmarco** [comment]
@alranel questa issue è ancora valida?

**Comment by bfabio** [comment]
@simevo +1

IMO, It's the SP's (or its tools) job to provide its own metadata. You need an SP implementation anyway, so it's not like we are inconveniencing the user by keeping it simple and not providing this feature. Personally, I would double guess my understanding of the system if the feature was there.

**Comment by peppelinux** [comment]
La compilazione "out-of-band" dei metadata è sempre stata una tentazione di chi si ritrova ad affrontare la validazione xsd SPID - me compreso - tuttavia mi sento di essere d'accordo con @bfabio, complessivamente non è solo il metadata la problematica da affrontare, segue poi la AuhtnRquest e a seguire come le Response vengono gestite dagli SP. 

Meglio affrontare la fully-compliance a livello di integrazione, anche se l'idea di creare un tool web avulso rimane valida seppur con bassa priorità
