### ISSUE TITLE
idptest non risponde

### ISSUE THREAD

**Issue by bamoruso** [italia/spid-testenv2#280]
Salve,
il server idptest.spid.gov.it non è più funzionante. Restituisce il seguente errore:
502 Bad Gateway
nginx/1.14.0 (Ubuntu)

**Comment by MatizMazzoni** [comment]
È così dal 23 dicembre! Spero possa essere ripristinato al più presto.

**Comment by MatizMazzoni** [comment]
@bamoruso 
Oggi, 9 gennaio 2020, ha ripreso a rispondere 200 OK.

**Comment by voidloop** [comment]
Ciao, 
sembra che idptest.spid.gov.it non sia funzionante.

502 Bad Gateway
nginx/1.14.0 (Ubuntu)

**Comment by wavewa** [comment]
Salve, avete notizie in merito? Come possiamo proseguire con i test di SPID?

**Comment by peppelinux** [comment]
Consigliamo vivamente di testare il vostro SP con una installazione locale di spid-testenv2
