### ISSUE TITLE
Errore "ValueError: Unicode ..." su idp online (https://idptest.spid.gov.it/)

### ISSUE THREAD

**Issue by mcolucci82** [italia/spid-testenv2#281]
Salve, 
come da istruzioni presenti al punto 4 di https://www.spid.gov.it/come-diventare-fornitore-di-servizi-pubblici-e-privati-con-spid#procedura-tecnica abbiamo provveduto a registrare il nostro SP con EntityID https://spid.comunestabia.it/spid/shibboleth, creati con l'immagine docker presente sul vostro repository https://github.com/italia/spid-shibboleth-proxy-docker

Al tentativo di accesso, tramite il seguente link https://spid.comunestabia.it/portale/public/login sul quale è configurato il metadata https://idp.spid.gov.it/metadata, riscontriamo il seguente errore:
**ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.**

Grazie

**Comment by MatizMazzoni** [comment]
Ciao,
ho notato che hanno rimosso tutti i meta da https://idp.spid.gov.it/admin/databasesprecord/.
Prova a ricaricarlo, facendo attenzione a non inserire il tag <?xml version="1.0" encoding="UTF-8" standalone="no"?>

**Comment by mcolucci82** [comment]
Ciao, grazie per la risposta. Adesso funziona correttamente.
