### ISSUE TITLE
Problemi integrazione SPID-TEST DOcker con Keycloak 9.0.0

### ISSUE THREAD

**Issue by audioqube** [italia/spid-testenv2#283]
Salve ho installato su windows il container Docker di spid test, lanciato e avviato correttamente ed ho configurato keycloak 9.0.0 (l'ultimissimo) per farlo funzionare a dovere con un service provider di prova e tutto funziona anche con keycloak come broker verso l'IDP SAMLtest.id e tutto funziona correttamente. Ho agiunto in keycloak l'autenticazione anche con lo SPID test ma all'atto dellaredirezione verso spidtest mi viene presentata una pagina con degli errori segnalati come attributi mancanti e cose del genere. COme si fa ad integrare correttamente keycloak con spid? Ci sono indicazioni su dove intervenire in keycloak a livello di codice per renderlo compatibile con spidtest? Ringrazio in anticipo.

**Comment by peppelinux** [comment]
Ciao @audioqube,
Non ho mai usato Keycloak ma ne conosco la fama.
I requisiti tecnici di SPID richiedono alcune attenzioni particolari sulla composizione dei metadata e AuthnRequest, di fatto un SP SAML2 tradizionale non supera la validazione.

Ad oggi non mi sembra che ci siano repository dedicati a keycloak e spid.
Valuta la possibilità di mascherare il tuo SP basato su keycloak con un proxy che vada a "normalizzare" le operazioni degli SP verso gli IdP SPID. E' solo un'idea, nulla di ufficiale, che condivido as-is

https://github.com/peppelinux/Satosa-Saml2Spid

**Comment by peppelinux** [comment]
qui troverai le risposte
https://github.com/italia/spid-keycloak-entando
https://github.com/lscorcia/keycloak-spid-provider
