### ISSUE TITLE
Ambiente di Test

### ISSUE THREAD

**Issue by Eduardo1977** [italia/spid-testenv2#285]
Buongiorno @alranel, quale ambiente di test è più aggiornato tra l'immagine docker da installare in locale e quello online idp.spid.gov.it ?  Quale ci consiglieresti per fare i test ?  
Grazie

**Comment by peppelinux** [comment]
Consigliamo vivamente di fare sempre i test in locale, mediante immagine Docker
non abbiamo alcuna visione della versione di spid-testenv2 attualmente in produzione presso AgID.
AgID è autonoma nel deploy e nella selezione della versione di spid-testenv2 da adottare
