### ISSUE TITLE
Algoritmo di firma deprecato

### ISSUE THREAD

**Issue by lorenzobersano** [italia/spid-testenv2#288]
Ciao a tutti!
Sto provando a fare un integrazione in locale tra l'IdP `spid-testenv2` e un SP implementato con `spid-passport`.

Sto riscontrando questo problema al redirect della richiesta di login
![Schermata 2020-07-09 alle 17 35 33](https://user-images.githubusercontent.com/20315075/87060300-a613d300-c20a-11ea-9b38-aa2b9aa9ba5c.png) .

Se provo a cambiare l'algoritmo di firma nel file `sp_metadata.xml` da `http://www.w3.org/2000/09/xmldsig#` a (ad esempio) `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256` riscontro quest'altro problema:
![Schermata 2020-07-09 alle 17 38 35](https://user-images.githubusercontent.com/20315075/87060623-099e0080-c20b-11ea-90d5-3c1b5cde2986.png)

E' già stato riscontrato questo problema? Come posso fare per risolvere?

**Comment by peppelinux** [comment]
Non è un problema particolare della piattaforma, piuttosto sha1 non è idoneo per SPID, usare almeno sha256
