### ISSUE TITLE
ansible role

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#29]
esiste https://github.com/italia/spid-sp-playbook (vedi anche https://forum.italia.it/t/playbook-per-configurare-sp-nginx-shibboleth-letsencrypt/131/13) ma è monolitico

propongo invece dei ruoli indipendenti che possano essere assemblati in un playbook dall'utente

uno potrebbe essere un ruolo che installa e configura questo test environment per l'identity provider

**Comment by alexrj** [comment]
Sì, assolutamente favorevole a scrivere anche ruoli Ansible per installare l'ambiente di test.

spid-sp-playbook è per installare Shibboleth, quindi un Service Provider; non ha relazione con l'Identity Provider di test.
