### ISSUE TITLE
Elemento KeyInfo>KeyName non ammesso nella Signature

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-testenv2#292]
Dalle Regole Tecniche, sezione Metadata:

```
Deve essere presente l’elemento <Signature> riportante la firma sui metadata. 
La firma deve essere prodotta secondo il profilo specificato per SAML (SAML-Metadata, cap. 3) 
utilizzando chiavi RSA almeno a 1024 bit e algoritmo di digest SHA-256 o superiore;
```

Relativamente all'elemento KeyInfo, le specifiche SAML-Metadata richiamate (https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf) rinviano alle specifiche XMLSig che prevedono un elemento opzionale detto "KeyName" (https://www.w3.org/TR/xmldsig-core2/#sec-KeyName).

Attualmente, SPID TestEnv, diversamente da SPID Validator, non accetta la presenza dell'elemento KeyName. Provvederò a fornire opportuna pull request.

**Comment by peppelinux** [comment]
Risolto qui
https://github.com/italia/spid-testenv2/commit/578a65cc4e22a736eba0c5038c0b6239ac293568
