### ISSUE TITLE
Errore di autorizzazione quando parte il Container

### ISSUE THREAD

**Issue by paolomarozzi** [italia/spid-testenv2#298]
Salve a tutti

vedo che non c'e' vita ma provo lo stesso.. 

Sono su Macosx Catalina

Creo il Container dentro Docker con le istruzioni dentro il Readme
sistemo il file di configurazione come indicato, genero le chiavi con Openssl
tutto come indicato

ma se faccio partire il Containter.. ho sempre questo errore.

ERRORE
Generating conf/idp.key and conf/idp.crt...
Generating a RSA private key
.........................................................................................................................+++++
...........................+++++
writing new private key to 'conf/idp.key'
req: Can't open "conf/idp.key" for writing, Operation not permitted

Qualcuno puo' aiutare?

**Comment by peppelinux** [comment]
Qui troverai le risposte
https://github.com/italia/spid-testenv2/blob/6ec41ce87b119489e2e27992fd03f46554e944d5/ansible/roles/spid-testenv2/tasks/main.yml
