### ISSUE TITLE
Validazione login

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#3]
Quando l'Idp di test riceve la AuthnRequest, dovrebbe validarla secondo le specifiche del protocollo SAML e secondo le [Regole Tecniche SPID](http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf). Gli errori (ERROR) e gli avvisi (WARNING), oltre ad essere loggati sulla console in STDOUT vanno anche visualizzati a video all'utente.

Esempi di possibili errori sono:
* `AuthnContextClassRef` con valore non valido
* `entityID` non corrispondente con quelli configurati nell'IdP di test
* firma mancante
* firma non valida
* certificato SP non corrispondente a quello presente nella configurazione
* `AssertionConsumerServiceIndex` non presente nella configurazione

Ogni singola prescrizione delle regole SAML e delle regole SPID deve essere tradotta in una regola di validazione.

Il codice deve essere scritto in modo che sia facile e pulito aggiungere altre validazioni dopo l'impementazione iniziale.

**Comment by alexrj** [comment]
Qui c'è [un esempio di checklist](https://github.com/italia/spid-docs/tree/master/resources-checklist) applicabile alle implementazioni dei Service Provider. Siccome qui stiamo sviluppando un Identity Provider, la checklist ovviamente sarebbe complementare (qui validiamo le AuthnRequest, non le generiamo, eccetera).

**Comment by alexrj** [comment]
Nell'[issue tracker dell'attuale ambiente di test](https://github.com/italia/spid-testenv/issues) sono raccolte varie problematiche di validazione o mancata validazione che il nuovo dovrebbe prevedere.

**Comment by umbros** [comment]
Aggiungo che, assieme all'errore o al warning deve essere mostrata la request o l'asserzione ed evidenziare, visivamente (evidenziato), in quale punto o punti si riscontra un malfunzionamento e come ci si aspetta debba essere presentata la specifica informazione. Da mostrare la request/asserzione sempre anche in caso di success.

**Comment by alexrj** [comment]
Questa issue è in attesa del merge di #31

**Comment by fmarco** [comment]
@alexrj mergiata
