### ISSUE TITLE
servizio operato dietro proxy: entityID e locations in metadata ?

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#30]
supponiamo di avere questa config:
- port: 8088
- host: 127.0.0.1 in modo che ascolti solo su localhost
- hostname: idp.simevo.com
- proxy (es. nginx) che lo gira sulla porta 443 es. https://idp.simevo.com (vantaggi: posso gestire i certificati SSL con certbot / letsencrypt, minimizzazione delle porte aperte, eventuale caching ...)

**problema**: il metadata generato dalla route `/metadata` in entityID, locations si riferisce a hostname:port del servizio python:
```
<ns0:EntityDescriptor
  xmlns:ns0="urn:oasis:names:tc:SAML:2.0:metadata"
  xmlns:ns1="http://www.w3.org/2000/09/xmldsig#"
  entityID="http://idp.simevo.com:8088">
```
dovrebbe essere:
```
  entityID="https://idp.simevo.com">
```
come la risolviamo ?

**Comment by alexrj** [comment]
Premesso che l'entityID non viene usato per nessuno scopo di comunicazione (è solo un identificativo unico) e che quindi la presenza della porta non causa nessun problema, forse possiamo toglierla per avere una URI più pulita. @fmarco

**Comment by fmarco** [comment]
@alexrj @simevo sì, direi che non ci sono problemi

**Comment by simevo** [comment]
Segnalo che se si accede all'IDP attraverso un url diversa da quella che si aspetta, si ottiene l'errore "OtherError: Not destined for me!":

![image](https://user-images.githubusercontent.com/8254819/42135532-88c78030-7d4c-11e8-8873-46653fdd3660.png)

**Comment by fmarco** [comment]
@simevo l'ultimo errore che hai postato adesso viene gestito dall'applicazione. 

@alexrj per l'entityid: lo costruiamo quindi solo utilizzando l'hostname, giusto?

**Comment by alexrj** [comment]
Propongo di fare così:

* l'entityID lo costruiamo solo con `hostname`;
* gli URL riportati nel metadata IdP (SSO, SLO) li costruiamo con `hostname:port`;
* se `hostname` contiene anche una porta (quindi tipo `localhost:8888`) la usiamo al posto di `port` per gli URL.

Lo scopo è quello di mantenere la configurazione facile com'è ora, ma di consentire a chi usa proxy (o Docker) di esporre la porta pubblica nel metadata IdP.

Cosa ne pensate?

**Comment by simevo** [comment]
quindi non ci sarebbe piú la chiave `port` ?

e per il protocollo come si fa ? `https` potrebbe essere settato a `false` (disabilita la modalità HTTPS nativa di python) ma il proxy potrebbe aggiungerlo ...

ci sono delle controindicazioni a lasciare `host` e `port` come sono per configurare il servizio python ma forzare direttamente l'entity ID completo di protocollo e porta (opzionale) nel config ? esempio:
```yaml
---
entity_id: https://idp.simevo.com
key_file: "idp.key"
cert_file: "idp.crt"
metadata:
  local:
  - "sp_metadata.xml"
  - "sp2_metadata.xml"
debug: true
host: 127.0.0.1
port: 8088
https: false
endpoints:
  single_sign_on_service: "/sso"
  single_logout_service: "/slo"
```

**Comment by fmarco** [comment]
@alexrj @simevo vogliamo sennò ripristinare un parametro `entity_id` più esplicito?
Intendo una configurazione come quella postata da @simevo nel suo ultimo commento.

**Comment by alexrj** [comment]
@simevo hai ragione.

In linea con quello che state proponendo voi propongo:

* `base_url`: es. `https://test-idp.spid.gov.it`, lo usiamo sia come entityID sia come base per gli endpoint dichiarati nel metadata
* `host`, `port`, `https`: li usiamo solo per configuare il web server locale del testenv2 ma non li esponiamo in nessun modo

Funziona?

**Comment by fmarco** [comment]
@alexrj ho aperto una PR per questa modifica
