### ISSUE TITLE
Certificato scaduto Ambiente di Test idptest.spid.gov.it

### ISSUE THREAD

**Issue by luimosca** [italia/spid-testenv2#302]
Salve,
da oggi  il certificato del sever idptest.spid.gov.it è scaduto.
Riuscite a dirmi se viene aggiornato? 

Potete avvisarmi quando viene sistemato perchè abbiamo problemi con l'autenticazione con le app in ambiente di test.
Grazie in anticipo per la disponibilità

Luigi Mosca

**Comment by damikael** [comment]
Il certificato SSL per idptest.spid.gov.it è stato rinnovato.

Saluti.
Michele D'Amico

**Comment by luimosca** [comment]
Ottimo, Grazie per il supporto
