### ISSUE TITLE
Errori random di validazione

### ISSUE THREAD

**Issue by luimosca** [italia/spid-testenv2#303]
Salve,
stiamo riscontrando errori di validazione quando viene chiamato il servizio idptest.spid.gov.it.

Si presentava stamattina, poi ad ora di pranzo funzionava e compariva la schermata di accesso, adesso compare di nuovo.
Provato a ricaricare il metadata ma niente, errore si presenta ancora.

Grazie in anticipo per il supporto

Luigi

**Comment by peppelinux** [comment]
vedi
https://github.com/italia/spid-testenv2/issues/315
