### ISSUE TITLE
Servizio di test "https://idptest.spid.gov.it/sso" non risponde

### ISSUE THREAD

**Issue by luimosca** [italia/spid-testenv2#315]
Salve,
il servizio di test "https://idptest.spid.gov.it/sso" non risponde e mi da l'errore"502 Bad Gateway"
Ci sono dei problemi?
Anche se provo ad accedere alla console (https://idp.spid.gov.it/admin/databasesprecord/ ) mi da lo stesso errore.
Grazie in anticipo per la disponibilità
Luigi Mosca

**Comment by nicolabeghin** [comment]
Buongiorno è possibile avere news al riguardo? Grazie

**Comment by peppelinux** [comment]
la disponibilità del servizio https://idptest.spid.gov.it/sso è fuori dagli scopi di questo progetto,
grazie per averlo notificato ma sono costretto a chiudere questa issue e chiedervi di di inoltrare la richiesta al gestore del servizio che è AgID
