### ISSUE TITLE
Integrazione installazione su Linux Ubuntu

### ISSUE THREAD

**Issue by deligant** [italia/spid-testenv2#319]
Volevo segnalare che prima di passare alla creazione dell'ambiente, bisogna avere installato

sudo apt install libpq-dev  python3.7-dev

altrimenti si inchioda al momento di installare i requisiti di partenza

Inoltra si deve ricordare di aggiornare con update-alternatives python che punti a python3.7

**Comment by peppelinux** [comment]
ciao, grazie per l'hint
questa piattaforma nasce docker, su distribuzioni differenti le dipendenze potrebbero variare.
Ad sempio io lo installo su python3.8 (vedi branch)

**Comment by deligant** [comment]
Grazie. Altro piccolo messaggio di errore che arria al lancio del server

/usr/lib/python3/dist-packages/virtualenv.py:1086: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

**Comment by peppelinux** [comment]
Se installi da master branch funziona anche py38

Grazie per le info, le considereremo per la prossima release
