### ISSUE TITLE
Scrivere test e configurare CI

### ISSUE THREAD

**Issue by fmarco** [italia/spid-testenv2#32]
Impostare la parte relativa a test e CI.

**Comment by simevo** [comment]
vedi https://github.com/italia/spid-php/issues/14

**Comment by alexrj** [comment]
Bisogna scrivere degli unit test che provano a validare diverse AuthnRequest.

**Comment by fmarco** [comment]
@alexrj ho aperto una PR che pone le basi per la parte di test

**Comment by alexrj** [comment]
@fmarco ho attivato TravisCI, al momento fallisce:
https://travis-ci.org/italia/spid-testenv2/builds/412878773

**Comment by alexrj** [comment]
@fmarco l'approccio che hai usato per scrivere i regression test mi sembra un po' fragile perché si basa sulla ricerca testuale del messaggio di errore: quando cambieremo il testo degli errori quei test non funzioneranno più.

Secondo me anziché fare chiamate HTTP al testenv dovresti più semplicemente fare refactoring del codice di validazione in modo che tu possa fare una chiamata diretta ad una classe, senza neanche bisogno di avviarlo il testenv. E non serve neanche andare a cercare specifici errori, perché in realtà per un regression test devi semplicemente accertarti che input corretto e input scorretto producano un risultato di validazione coerente. Potresti fare semplicemente così:

```python
v = authrequest_validator()

badRequest1 = generateAuthnRequest(...)
self.assertFalse(v.validate(badRequest1).is_valid)

badRequest2 = generateAuthnRequest(...)
self.assertFalse(v.validate(badRequest2).is_valid)

goodRequest1 = generateAuthnRequest(...)
self.assertTrue(v.validate(goodRequest1).is_valid)
```

(Nella mia testa `v.validate()` restituisce una classe `ValidationResult` che rappresenta in forma astratta gli errori rilevati, così che si possano passare al front-end oppure archiviare per essere poi letti via API come ci dicevamo per lo scenario 3.)

**Comment by alexrj** [comment]
Io di solito metto nei commenti, vicino ad ogni regression test, l'URL della corrispondente issue GitHub. Secondo me è opportuno farlo anche in questo caso, così ce le possiamo rivedere una ad una ed assicurarci che la logica copra il caso di riferimento.

**Comment by fmarco** [comment]
@alexrj Sì, concordo, al momento ho utilizzato la strada del controllo frontend (più strutture dati BE) per velocizzare la scrittura dei test e implementare una prima mandata. 
L'idea è quella di separarli in classi / moduli suddivisi per tipologia e lato testenv avere un singolo metodo che restituisca la validazione (purtroppo al momento alcune validazioni specifiche devono essere intercettate lato pysaml2), cosa che probabilmente sarà possibile appena verrà implementata anche la validazione XSD.
Ottima idea quella dei commenti!

**Comment by fmarco** [comment]
@alexrj pensi che, in base all'attuale struttura della suite di test, si possa chiudere questa issue?

**Comment by fmarco** [comment]
@alexrj credo che a questo punto si possa chiudere :)

**Comment by fmarco** [comment]
@alexrj chiudo
