### ISSUE TITLE
Errore in accesso pagina login Spid

### ISSUE THREAD

**Issue by archetipo** [italia/spid-testenv2#36]
Passi eseguiti su browser Chrome e Firefox :

* Sp richeide metadata a IdP test env
* Sp esegue chiamata all'endpoint sso configurato con AuthnRequest valida per esecuzione login
* Idp  test env risponde :

>  Http-Redirect
>  Request key: None

risulta quindi impossibile eseguire il flusso di login

**Comment by alexrj** [comment]
Credo sia utile avere il tuo config.yaml del testenv2

**Comment by archetipo** [comment]
si ecco la configurazione del config.yaml:
`

debug: true

host: 0.0.0.0

port: 8088
hostname: "spid-testenv"
https: false

endpoints:
  single_sign_on_service: "/sso"
  single_logout_service: "/slo"

key_file: "idp.key"
cert_file: "idp.crt"


`

**Comment by fmarco** [comment]
@archetipo non vedo la sezione metadata nel tuo config.yaml

**Comment by archetipo** [comment]
il problema era dovuto al fatto che la richiesta Authn non era costruita nel modo corretto.
eseguendo la richiesta in modo corretto sono riuscito a completare tutto il giro si autenticazione.

grazie

**Comment by fmarco** [comment]
@archetipo D'accordo, pensi che si possa chiudere?

**Comment by archetipo** [comment]
@fmarco si si grazie

**Comment by alexrj** [comment]
@fmarco in realtà se la AuthnRequest non era costruita in modo corretto il testenv2 dovrebbe aiutare l'utente a capire il problema e a correggerlo. La risposta ottenuta da @archetipo non va bene

**Comment by alexrj** [comment]
@archetipo cosa c'era di non corretto nella richiesta che generavi?

**Comment by archetipo** [comment]
@alexrj  inviavo la richiesta con il solo parametro "SAMLRequest" firmata, ma senza i parametri "SigAlg" e "Signature". 
Ieri ho aggiornato il codice della PR #31 all'ultimo commit e testato il flusso di login, quindi mi veniva restituito il messaggio "Messaggio SAML non firmato." 
Ho aggiornato il mio Sp di test creando la chiamata in modo corretto cioe' creando il link del redirect che comprendesse tutti i parametri:  

"SAMLRequest":AuthnRequest,  "SigAlg": algoritmo di firma, e "Signature" : la firma

quindi sono riuscito a effettuare l'intero ciclo di login.

**Comment by alexrj** [comment]
@fmarco il testenv2 deve rilevare e spiegare anche questa fattispecie di richiesta non valida

**Comment by fmarco** [comment]
@alexrj attualmente questa tipologia di errore dovrebbe essere già intercettata

**Comment by alexrj** [comment]
@fmarco confermo che esce un errore "Messaggio SAML non firmato.". Secondo te possiamo renderlo ancora più esplicito e dire che mancano i parametri Signature e/o SigAlg, necessari per le richieste HTTP-Redirect?

**Comment by fmarco** [comment]
@alexrj Ho pushato un fix per questa cosa (correggendo /aggiungendo anche i test).

**Comment by alexrj** [comment]
Confermo
