### ISSUE TITLE
Lettura remota metadati SP

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#37]
Quando si configurano i metadati del SP usando l'elemento `remote` il testenv2 li legge da una URL remota (è comodo per leggerli direttamente da un endpoint esposto dal SP invece di salvarli in locale).

Sarebbe utile specificare nei commenti del config.yml se questa lettura avvenga al lancio del testenv2, oppure alla prima AuthnRequest, oppure ad ogni singola richiesta (ovvero senza alcun caching). Sarebbe molto comodo se fosse quest'ultimo caso.

**Comment by fmarco** [comment]
@alexrj attualmente la lettura viene effettuata al lancio del testenv per via del logica flusso standard previsto in pysaml2. Se vogliamo impostare la lettura dei metadata ad ogni richiesta posso preparare una modifica.

**Comment by alexrj** [comment]
Sono indeciso ma credo sia utile leggerli ad ogni richiesta, senza dover riavviare il testenv2.
