### ISSUE TITLE
Risposte custom

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#4]
Per consentire agli sviluppatori di testare la sicurezza delle proprie implementazioni è necessario verificare che effettuino il parsing e la validazione delle Response da parte dell'IdP in modo corretto e completo, senza fidarsi dell'input.
Bisogna quindi fare in modo che l'IdP di test possa restituire delle Response e delle asserzioni con errori che il Service Provider deve intercettare.

Una buona lista di circostanza da testare è quella [riportata in questa checklist](https://github.com/italia/spid-docs/tree/master/resources-checklist) sotto la voce "Response/Assertion parsing": ciascuna di quelle problematiche deve poter essere testabile. Anche se la lista è un po' lunga credo sia utile consentire di testarle tutte una per una.

Mi immagino che nella schermata di login dell'IdP ci sia anche un riquadro aggiuntivo con cui si possa personalizzare la Response scegliendo una di queste anomalie (ad esempio: manda una firma sbagliata, ometti un attributo ecc.).

**Comment by alexrj** [comment]
@umbros, ti vengono in mente altri possibili anomalie da introdurre?

**Comment by alexrj** [comment]
Inoltre, molto importante, bisogna poter indicare il livello SPID (`AuthnContextClassRef`) da dare in risposta, visto che secondo le regole SPID non è detto che l'IdP restituisca lo stesso livello chiesto nella AuthnRequest ma anche qui c'è una libertà e delle condizioni che vanno testate a pieno.

**Comment by umbros** [comment]
Un'implementazione da contemplare è quella di poter far si che l'IdP di test restituisca asserzioni con "errori" quali certificato scaduto o non presente sul metadata e, di fatto, su tutti i fattori di sicurezza saml di cui un SP deve tenere conto per trustare o meno un IdP. Stessa cosa, al contrario deve fare l'SP di test (altra fase di sviluppo).

Riguardo l'AuthnContextClassRef, se il comparison è != da exact, ovvero maximum o minimum, potrebbe essere diverso dal livello richiesto ovvero un sp richiede autenticazione minimum livello 2, l'utente potrebbe accedere con livello 3. In questo caso l'SP può ignorare il valore ma controllare che comunque rispetti la comparison.

**Comment by alexrj** [comment]
Ho aggiunto alla [checklist](https://github.com/italia/spid-docs/blob/master/resources-checklist/README.md) anche la verifica del parametro `RelayState`, quindi nelle risposte custom bisogna anche prevedere l'invio di un `RelayState` difforme da quello inviato con la AuthnRequest.

**Comment by fmarco** [comment]
@alexrj Ciao, a livello di interfaccia (frontend) potremmo includere dei field (eventualmente nascosti tramite pulsante mostra/nascondi) nello stesso form del login per decidere quali elementi rimuovere o rendere errati. In alternative si possono spostare tali scelte nella schermata di riepilogo in cui si conferma la response da inviare al SP.

**Comment by fmarco** [comment]
@alranel aggiunta la possibilità di gestire risposte custom nel form di login (andrà sistemato un po' graficamente)
