### ISSUE TITLE
Consentire di creare utenti non legati a nessuno specifico Service Provider

### ISSUE THREAD

**Issue by davidlibrera** [italia/spid-testenv2#40]
Al momento quando si crea un utente tramite il form all'indirizzo

```/add-user```

tra i campi principali abbiamo, oltre ad utente e password, anche un ID del service provider.
Quando si inseriscono le credenziali l'accesso viene effettuato se il dominio di provenienza (l'SP) corrisponde a quello associato all'utente.

A parer mio questo confonde un po' perché nelle specifiche SPID non c'è nessun vincolo tra credenziali e SP. Inoltre è un campo che tiene conto di porte, protocolli e slash finali, rendendo spesso difficile configurare.

E' possibile rimuoverlo e, per autenticare un utente, accettare utente e password senza controllare il service provider?

**Comment by alexrj** [comment]
Concordo. Credo che @fmarco l'abbia fatto pensando ad un contesto multi-utente (testenv erogato da AgID) in cui coesistono più Service Provider, ma questa cosa dovrebbe essere opzionale.

Ecco alcune azioni da fare:

1. Consentire di creare utenti senza SP, quindi validi per tutti i SP configurati.
2. Esporre un dropdown per configurare il SP in modo da non doverlo digitare a mano.
3. Fornire un set minimo di utenti preconfigurati nel file users.json.

**Comment by alexrj** [comment]
4. Mostrare gli utenti configurati (con tutti i relativi dati), credo che possiamo farlo direttamente in `/add-user` che a questo punto potrebbe rinominarsi `/users`.

**Comment by fmarco** [comment]
@alexrj @davidlibrera sì, era un "vincolo" introdotto per avere una situazione multiutente base.

Ok per le migliorie! Gli utenti di default li generiamo alla creazione del file, giusto? non è un'operazione esplicita da parte dell'utente immagino.

**Comment by alexrj** [comment]
Sì, esatto, li generiamo alla creazione del file.

**Comment by alexrj** [comment]
Va bene così e non serve un livello di navigazione. Bisognerà fare un minimo di lavoro di UI ma per adesso va bene così. Dovresti però correggere il menu dove è rimasto "Aggiungi utenti"

**Comment by alexrj** [comment]
Il dropdown relativo al Service Provider dovrebbe avere l'elemento vuoto altrimenti non si può selezionare:

```html
<select>
    <option value="">- tutti -</option>
    <option value="1">Service Provider 1</option>
    <option value="2">Service Provider 2</option>
</select>
```

**Comment by fmarco** [comment]
@alexrj pushato un fix per il menù.
L'elemento vuoto del dropdown è già gestito, vogliamo però rendere più esplicita la cosa nel modo che hai evidenziato tu?

**Comment by alexrj** [comment]
Per com'è adesso l'opzione vuota non si può selezionare. Secondo me dovresti cambiare il primo elemento da:

```html
<option disabled="" selected="" value=""> -- Scegli un service provider (Opzionale) -- </option>
```

a:

```html
<option value="">- tutti -</option>
```

**Comment by fmarco** [comment]
@alexrj pushato minfix su master
