### ISSUE TITLE
Metadata IdP

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#41]
Nei metadati IdP esposti dal testenv all'URL `/metadata` vedo che l'attributo `WantAuthnRequestsSigned` è impostato a `false`. Dovrebbe essere impostato a `true` in modo da simulare più correttamente cosa avviene in produzione.

`<ContactPerson>` non è previsto dalle Regole Tecniche SPID, mentre `<Organization>` è facoltativo quindi non avendo dati utili per configurarlo direi che possiamo toglierlo.

**Comment by fmarco** [comment]
@alexrj  ho rimosso ContactPerson e Organization (ho pushato già il fix), mentre sto indagando su come far gestire correttamente WantAuthnRequestsSigned a pysaml2

**Comment by alexrj** [comment]
Per la firma del metadata puoi vedere questo codice: https://github.com/italia/spid-metadata-builder

**Comment by alranel** [comment]
Ad oggi `WantAuthnRequestsSigned` è impostato a `true`.
