### ISSUE TITLE
Service Provider non configurato

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#42]
Quando si invia una AuthnRequest contenente un `Issuer` che non corrisponde a nessun Service Provider configurato nel testenv si ottiene questa schermata:

![Errore](https://user-images.githubusercontent.com/594957/42040567-3c66d122-7af0-11e8-9574-9cd8073e2b6b.png)

Mi aspetterei invece di vedere la stessa schermata che mostra gli errori di validazione della AuthnRequest, con spiegato il problema.

**Comment by fmarco** [comment]
@alexrj questo bug è già gestito in nella PR https://github.com/italia/spid-testenv2/pull/31 :)

**Comment by alexrj** [comment]
@fmarco ho testato con il branch `feature/issue-3-validazione-login` (PR #31) ma ancora non va: non mi mostra nessun errore nella tabella errori.
Questa cosa deve far parte della validazione del tag `<Issuer>`.

**Comment by alexrj** [comment]
Ho appena provato con master inviando un Issuer non corrispondente all'entityID del metadata SP e viene accettato senza errori, visualizzo il form di login.

**Comment by alexrj** [comment]
Secondo me sarebbe bene unificarli, soprattutto perché per poter scrivere degli unit test ci servirà una unica funzione `validate_authnrequest()` (nome di fantasia) che poi al suo interno può essere implementata anche in modo articolato usando varie strategie di validazione, ma che all'esterno dovrebbe restituire gli errori in un modo unitario. Partendo da questo presupposto puoi tranquillamente mostrarli con un solo template

**Comment by fmarco** [comment]
@alexrj potresti allegarmi authnrequest e vers. di python?

**Comment by alexrj** [comment]
AuthnRequest:

```
<saml2p:AuthnRequest Version="2.0" AssertionConsumerServiceIndex="0" ID="8388a090e3cc852d3764349b267fa569" AttributeConsumingServiceIndex="1" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" IssueInstant="2018-07-10T15:08:34Z" Destination="http://localhost:8088/sso" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://localhost/xxxxxx">https://localhost/xxxxxx</saml2:Issuer><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2p:RequestedAuthnContext Comparison="minimum"><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext></saml2p:AuthnRequest>
```

Estratto dal metadata SP:

```
<md:EntityDescriptor 
    xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"  
    xmlns:ds="http://www.w3.org/2000/09/xmldsig#"  
    entityID="https://localhost/"  
    ID="_681a637-6cd4-434f-92c3-4fed720b2ad8">
```

Python 2.7.10

**Comment by fmarco** [comment]
@alexrj questo errore è stato gestito in uno dei commit recenti, va però articolato meglio e spostato in nella tabella giusto? (mi confermi intanto che vedi la schermata di errore generica contenente il messaggio "destinazione messaggio errata" ?)

**Comment by alexrj** [comment]
Al momento esce questo:

![screen shot 2018-07-10 at 17 38 28](https://user-images.githubusercontent.com/594957/42521043-1b4b1882-8468-11e8-9d10-0ece1f7855e6.png)

**Comment by fmarco** [comment]
@alexrj pushato un fix, riprova pure

**Comment by fmarco** [comment]
@alexrj hai avuto modo di riprovare?

**Comment by alexrj** [comment]
Confermo che ora appare la seguente schermata di errore:

![screen shot 2018-08-06 at 22 38 27](https://user-images.githubusercontent.com/594957/43739804-8f269616-99c9-11e8-812f-e4bb0328dfb6.png)

**Comment by alexrj** [comment]
Tuttavia c'è un problema.

Se mando una AuthnRequest che contiene un Issuer sconosciuto, e chiedo un AttributeConsumingService ottengo questo errore:

![screen shot 2018-08-06 at 22 40 29](https://user-images.githubusercontent.com/594957/43739900-e812d212-99c9-11e8-8b87-c4f4ce69ca1a.png)

Evidentemente non riuscendo a trovare il Service Provider compone una lista vuota di valori attesi e quindi questa validazione fallisce. Però questo messaggio di errore è molto fuorviante. La validazione dovrebbe andare in ordine di priorità e cominciare dall'Issuer perché molte delle validazioni successive dipendono da esso.

**Comment by fmarco** [comment]
@alexrj pushato fix e test su master

**Comment by alexrj** [comment]
Confermo
