### ISSUE TITLE
Attributi richiesti dal SP

### ISSUE THREAD

**Issue by davidlibrera** [italia/spid-testenv2#43]
L'elenco degli attributi forniti dall'Identity Provider dipende unicamente dagli attributi settati all'interno dell'IdP stesso invece di essere dipendenti dai campi
```<md:RequestedAttribute ...>```
del metadata lato SP

Nel caso qui sotto in fase di creazione utente ho lasciato solo il codice fiscale, mentre il metadata del service provider non riporta alcun attributo

![screenshot from 2018-06-28 16-51-54](https://user-images.githubusercontent.com/400256/42042905-7422281e-7af5-11e8-9ad2-a3611171aa81.png)

**Comment by alexrj** [comment]
@davidlibrera Se capisco bene, questa segnalazione vuol dire che il parametro `AttributeConsumingServiceIndex` della AuthnRequest viene ignorato e che quindi il testenv2 restituisce sempre tutti gli attributi?

**Comment by davidlibrera** [comment]
Si, il parametro ```AttributeConsumingServiceIndex```
sembra essere ignorato e gli attributi restituiti sono tutti quelli non nulli

**Comment by umbros** [comment]
Non è corretto se non viene indicato un AttributeConsumingServiceIndex la request deve generare errore

**Comment by fmarco** [comment]
@umbros @alexrj sulle regole tecniche però è specificato che in alternativa può essere utilizzata la coppia  AssertionConsumerServiceURL + ProtocolBinding, o sbaglio? se ciò è corretto bisognerebbe verificare la presenza secondo una formula del tipo: AttributeConsumingServiceIndex OR ( AssertionConsumerServiceURL AND ProtocolBinding ), però è meglio chiarire questo punto.

**Comment by alexrj** [comment]
@fmarco stai facendo confusione tra due parametri che hanno nomi simili:

* `AttributeConsumingServiceIndex`: indica il gruppo di attributi da rilasciare nell'asserzione
* `AssertionConsumerServiceIndex`: indica l'endpoint dove l'utente deve andare dopo il login

La logica di validazione è:

* `AttributeConsumingServiceIndex`: opzionale (@umbros le regole tecniche dicono che è opzionale! o è stato cambiato in qualche avviso?)
* `AssertionConsumerServiceIndex` OR (`AssertionConsumerServiceURL` AND `ProtocolBinding`)

**Comment by fmarco** [comment]
@alexrj ho aggiornato la logica di validazione

**Comment by fmarco** [comment]
@alexrj aggiunti test
