### ISSUE TITLE
Non ritorna all'AssertionConsumerService richiesto

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#45]
Al termine del login, il testenv2 mi rimanda ad un URL non valido (`http://<hostname testenv2>/None`) anziché all'AssertionConsumerService del mio Service Provider.

Il metadata del SP contiene:

```
        <md:AssertionConsumerService  
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"  
            Location="https://localhost/spid-acs"  
            index="0"  
            isDefault="true" /> 
```

La AuthnRequest è la seguente:

```
<saml2p:AuthnRequest IssueInstant="2018-06-28T15:49:38Z" AssertionConsumerServiceIndex="0" AttributeConsumingServiceIndex="1" Destination="http://localhost:8088/sso" ID="a0a50e3ee82ecb44365a0b4bec0374e0" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://localhost/">https://localhost/</saml2:Issuer><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2p:RequestedAuthnContext Comparison="minimum"><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext></saml2p:AuthnRequest>
```

**Comment by fmarco** [comment]
@alexrj ho pushato un fix su master per risolvere questo problema

**Comment by alexrj** [comment]
Ad oggi non posso testare questa issue perché #54 mi blocca

**Comment by fmarco** [comment]
@alexrj riprova pure (vedi ultimo commento in #54 )

**Comment by alexrj** [comment]
Testato ora, funziona.

**Comment by alexrj** [comment]
Questo bug si presenta di nuovo.

Inviando questa AuthnRequest, dopo aver confermato gli attributi vengo reindirizzato a `/None`:

```xml
<saml2p:AuthnRequest Destination="http://localhost:8088/sso" IssueInstant="2018-07-19T11:29:49Z" ID="23e77ad3a97ce0e5f04e610e3b391a44" ForceAuthn="false" AssertionConsumerServiceURL="http://localhost:3000/spid-sso" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0" AttributeConsumingServiceIndex="0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://localhost/">https://localhost/</saml2:Issuer><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2p:RequestedAuthnContext Comparison="exact"><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext></saml2p:AuthnRequest>
```

Lo stesso comportamento si verifica anche inviando `AssertionConsumerServiceIndex` al posto di `AssertionConsumerServiceURL`.

Questo è uno stralcio del metadata SP:

```xml
        <md:AssertionConsumerService  
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"  
            Location="http://localhost:3000/spid-sso"  
            index="0"  
            isDefault="true" /> 
```

**Comment by fmarco** [comment]
@alexrj non riesco a riprodurre l'errore, sei su qualche branch / commit / versione di python particolare?

**Comment by marcoz-tsn** [comment]
Stesso problema qui, ultima versione del test environment 2 (compreso commit odierno di spid-testenv.py):
![image](https://user-images.githubusercontent.com/10044374/43593900-3dbd06d2-9679-11e8-939d-ac327edaaf8c.png)


Il mio ACS è così definito (è il SP di spid-dotnet-sdk):
        <md:AssertionConsumerService  
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"  
            Location="http://www.tpcware.com/spid/acs"  
            index="0"  
            isDefault="true" />

**Comment by sanjioh** [comment]
@alexrj @marcoz-tsn: Ciao, potreste verificare che il comportamento che avete notato si verifichi ancora con l'ultimo master? La validazione dell'AuthnRequest dovrebbe essere tale da intercettare l'errore e mostrare un messaggio esplicito a riguardo. Grazie!

**Comment by alexrj** [comment]
Io non riesco più a riprodurre il problema, quindi credo sia risolto.
@marcoz-tsn puoi confermare?

**Comment by marcoz-tsn** [comment]
@sanjioh @alexrj : torno da una pausa ferie, ho ritestato la condizione che avevo segnalato ed ora ricevo correttamente un errore come questo:

Elemento | Dettagli errore
-- | --
samlp:AuthnRequest | AttributeConsumingServiceIndex<br/>° 1 non corrisponde a nessuno dei valori contenuti in ['0']

Grazie per il fix
