### ISSUE TITLE
Validazione AuthnRequest

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#46]
Ho provato ad inviare una AuthnRequest contenente un `AssertionConsumerServiceIndex` con valore non valido (ho messo 2 ma nel mio metadata SP quell'AssertionConsumerService non c'è), eppure non mi viene mostrato nessun errore e visualizzo il form con username/password.

Analogamente, anche le seguenti prove non mi hanno mostrato alcun errore (come invece mi aspetterei visto che sono valori non validi):

* `AttributeConsumingServiceIndex="11"`
* `<saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL4</saml2:AuthnContextClassRef>` (livello 4 di SPID non esistente!)

@fmarco, queste validazioni forse non sono su master?
Non ho fatto altre prove oltre a quelle qui riportate però bisogna verificare ogni singolo elemento dell'XML.

**Comment by alexrj** [comment]
Ho appena provato con il branch `feature/issue-3-validazione-login` e queste validazioni non sono presenti neanche lì.

**Comment by alexrj** [comment]
Inoltre mi sembra che non ci sia nessuna validazione rigida sulla struttura del messaggio XML. Se qualcuno invia dei tag in più (ad esempio `<Ciao>`) in posti dove non sono attesi li rileviamo?

Se così non fosse, un modo semplice è quello di applicare la validazione via xsd, anche se i messaggi restituiti da LibXML non sono il massimo della leggibilità.

**Comment by fmarco** [comment]
@alexrj `AuthnContextClassRef` viene controllato `feature/issue-3-validazione-login`, per quanto riguarda invece `AttributeConsumingServiceIndex` sto effettuando dei controlli in pysaml2

**Comment by fmarco** [comment]
@alexrj al momento (vedi #31 ) è pysaml2 che effettua il parsing iniziale, potremmo a questo punto strutturare degli xsd per ogni tipologia di messaggio, basandoci su quelli SAML2 e modificandoli con le restrizioni (o, ancora meglio, esistono già? :) )

**Comment by fmarco** [comment]
@alexrj Ho rafforzato il controllo su AttributeConsumingServiceIndex, controlla pure

**Comment by alexrj** [comment]
Ho appena provato inviando `AttributeConsumingServiceIndex="99"` e `https://www.spid.gov.it/SpidL4` e vengono ancora accettati senza errori.

**Comment by fmarco** [comment]
@alexrj confermo che il controllo sul livello spid funziona, sto ancora sistemando / indagando sulla parte AttributeConsumingServiceIndex

**Comment by alexrj** [comment]
Ho testato, confermo che il che il controllo sul livello SPID funziona ma manca ancora `AttributeConsumingServiceIndex`.
