### ISSUE TITLE
valore di AuthnContextClassRef

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#49]
nelle regole tecniche pag 10 c'è un esempio di valore per `RequestedAuthnContext.AuthnContextClassRef`:
```
<samlp:RequestedAuthnContext Comparison="minimum">
  <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:SpidL2</saml:AuthnContextClassRef>
</samlp:RequestedAuthnContext>
```
se la mando così dà `IndexError`.

procede solo se `AuthnContextClassRef` vale ad esempio: `https://www.spid.gov.it/SpidL1`

**Comment by archetipo** [comment]
dovresti provare a fare il test creandoti un branch locale di questo progetto che comprenda anche la #31 
a me così funziona.

**Comment by davidlibrera** [comment]
Come ho riportato nella issue sulle regole tecniche, su questo aspetto la versione html e la versione pdf suggeriscono 2 metodi differenti per specificare ```AuthnContextClassRef```

Per poter risolvere questa Issue direi sia necessario prima stabilire quale delle 2 modalità sia quella corretta.

**Comment by archetipo** [comment]
si ho letto la discrepanza, nell' [AuthnRequest](https://github.com/italia/spid-regole-tecniche/blob/b0759ed5fb7fb387c0009f09e687817948e0c046/src/code-samples/authnrequest.xml) di esempio è riportato quanto descritto nella versione Html, per i test mi sono basato su questa modalità, ma non saprei dire quale sia la forma corretta, o come si decida.

**Comment by davidlibrera** [comment]
@alexrj Serve una direttiva all'alto :smile:

**Comment by alexrj** [comment]
Ignorate le regole in HTML (sono in lavorazione) e considerate unicamente le regole in PDF più gli [avvisi](https://www.agid.gov.it/it/piattaforme/spid/avvisi-spid) che le emendano.

In particolare l'[avviso n. 5](https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid-avviso-n5-regole-tecniche-errata-corrige.pdf) dice che il valore corretto è `https://www.spid.gov.it/SpidL1` e via dicendo.

**Comment by simevo** [comment]
perfetto, allora è corretto il testenv2 !

**Comment by fmarco** [comment]
@alexrj  Sì, infatti come valori ho impostato quelli in RequestedAuthnContext.
