### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#5]
Anche se le regole tecniche SPID impongono che tutti gli Identity Provider operino solo in HTTPS, al fine di far girare l'ambiente in locale credo sia molto utile consentire anche di farlo girare in HTTP semplice per non avere problemi di certificati (non ottenibili per _localhost_). Nella configurazione ci vuole quindi un parametro anche per http/https.

**Comment by umbros** [comment]
https: tls1.2
valuterei la cosa perchè, di fatto, un self signed può essere autorizzato dall'utente lato browser.

**Comment by alexrj** [comment]
Può essere autorizzato, ma può essere laborioso come documentato in [questa issue](https://github.com/italia/spid-testenv/issues/6). Facendolo girare su localhost non c'è bisogno di HTTPS, togliamo una difficoltà agli sviluppatori :) 
(Trattandosi di un IdP di test non c'è alcun rischio che la modalità HTTP possa entrare in produzione in qualche modo)

**Comment by alexrj** [comment]
Questa cosa è stata implementata, quindi chiudo la issue
