### ISSUE TITLE
Il tasto "Annulla" non esegue nessuna azione

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#50]
In fase di login, se l'utente preme il tasto "Annulla" anziché completare il login, non succede nulla.

Invece si dovrebbe ritornare all'AssertionConsumerService del Service Provider chiamante passando il codice di errore specificato dalla tabella errori (vedere sito AgID, c'è la tabella errori).

**Comment by fmarco** [comment]
@alexrj ho aperto una PR per gestire questa issue

**Comment by fmarco** [comment]
@alexrj mergiata PR

**Comment by fmarco** [comment]
@alexrj si può chiudere?

**Comment by alexrj** [comment]
Confermo
