### ISSUE TITLE
Supporto multi-utente

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#6]
In questa issue tracciamo le caratteristiche del supporto multi-utente previsto per la seconda fase di sviluppo. Nella prima fase ci focalizziamo sulla realizzazione di un ambiente di test che gli sviluppatori possano eseguire in locale oppure installare su un proprio server (milestone [1.0](https://github.com/italia/spid-testenv2/milestone/4)). Poi passeremo all'aggiunta delle funzionalità necessarie all'erogazione centralizzata dell'ambiente di test.

Ciascun utente dovrà poter entrare e creare/modificare/cancellare i propri Service Provider.

Funzionalità necessarie:

* login utenti (SSO con GitHub?)
* interfaccia di backoffice per amministrazione
* database per utenti e relative configurazioni Service Provider

Da valutare:

* logging messaggi SAML e loro visualizzazione ordinata nel pannello di backoffice?
* interfaccia di amministrazione?

**Comment by umbros** [comment]
- login utenti: senza autenticazione se utilizzato localmente con autenticazione SPID se utilizzato online
- backoffice: sempre presente offline/online
- su versione locale potremmo utilizzare anche un sqlite o un qualsiasi sistema di database compresi file testuali (csv, json, yaml) su versione online utilizziamo postgresql
- il logging dei messaggi sarà possibile sia su un apposito pannello di backoffice che sulla maschera stessa di autenticazione mostrando il processamento delle varie request e asserzioni (mostrare success, warning, error)
- l'interfaccia di amministrazione, come detto, dovrà essere presente su versione online e offline.

Ovviamente parliamo di seconda fase. Prima fase convenuto tutto su file di conf.

**Comment by alexrj** [comment]
Maggiori dettagli di seguito, in linea con quanto scritto sopra.

Dobbiamo aggiungere il supporto per registrare in un database le seguenti informazioni:

1. utenti testenv (SSO GitHub)
2. metadata SP collegati agli utenti di cui al punto 1 (tali metadata saranno caricati _in aggiunta_ a quelli configurati staticamente in config.yaml)
3. utenti SPID (attualmente registrati in users.json)

Questo database può essere ad esempio un set di file JSON (come l'attuale users.json) oppure un PostgreSQL.

In config.yaml aggiungiamo le seguenti opzioni:

* `backoffice` (true/false): abilita/disabilita l'interfaccia di backoffice
* `database`: contiene le informazioni relative al database (file o Postgres)
* `github_sso`: contiene i dati per l'integrazione con GitHub

L'interfaccia di backoffice consiste in:

* login SSO GItHub
* caricamento/modifica/eliminazione metadata SP collegati all'utente corrente
   * basta una textarea per caricare il metadata completo (con validazione), poi in futuro faremo un'interfaccia più guidata
* gestione utenti SPID collegati all'utente corrente

L'interfaccia di amministrazione la mettiamo in cantiere in un secondo momento (così diamo priorità alle altre cose più urgenti); per ora gestiremo intervenendo direttamente sul database con tool generici.

**Comment by alexrj** [comment]
Ho creato issue di dettaglio per le varie fasi necessarie:

* #129: database
* #130: interfaccia di backoffice
* #131: interfaccia di amministrazione

**Comment by alranel** [comment]
Ad oggi abbiamo il supporto per un database PostgreSQL, che consente di sviluppare eventuali interfacce esternamente.
