### ISSUE TITLE
IssueInstant deve validare timestamp ISO 8601 con millisecondi

### ISSUE THREAD

**Issue by cloudify** [italia/spid-testenv2#61]
Questo attributo è un timestamp valido ISO 8601 ma il tool non lo valida (errore `la data non è in formato UTC`):

```
IssueInstant="2018-07-11T07:28:57.935Z"
```

Tra l'altro l'errore e' di per se incorretto perche' dice che non e' in UTC, quando invece lo e', il problema e' che il timestamp viene interpretato con il codice:

```python
datetime.strptime(date, '%Y-%m-%dT%H:%M:%SZ')
```

che non accetta un timestamp con millisecondi.

**Comment by alexrj** [comment]
Confermo. I millisecondi sono ammessi dal tipo `xs:dateTime` richiesto per `IssueInstant`.

Dovrebbe essere sufficiente questa espressione regolare: `^20[1-9][0-9]-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z$`.

**Comment by alexrj** [comment]
Anche se in effetti è meglio fare il parsing, così verifichiamo che l'istante indicato non sia troppo distante dall'ora attuale (le regole tecniche non specificano un delta, io direi che per ora possiamo arbitrariamente mettere 2 minuti).

**Comment by fmarco** [comment]
@alexrj @cloudify ho pushato un fix per la gestione di questo flusso.
Ho risolto utilizzando una utility di pysaml2 che implementa già il controllo che avrei voluto fare. Come delta la libreria utilizza un giorno, che facciamo? Settiamo un valore custom nostro o per ora teniamo quello?

**Comment by alexrj** [comment]
Un giorno mi sembra troppo. Al momento questa tolleranza è lasciata alle policy di ciascun Identity Provider (auspicabilmente andremo a definire un valore ufficiale quanto prima), e quindi è meglio essere restrittivi nel testenv per garantire la massima interoperabilità con gli IdP reali. Quindi propongo di andare su 2 minuti.

**Comment by fmarco** [comment]
@alexrj ho aggiornato master con un commit in cui miglioro questa gestione

**Comment by fmarco** [comment]
@alexrj issue testata in #78)
