### ISSUE TITLE
AuthnRequest: ID non viene validato correttamente

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#63]
Ho inviato una AuthnRequest il cui attributo ID è `28af4fe5a2923bd47d5d01ea07a255b5`.

Questo valore non è valido perché la definizione del tipo XSD `NCName` prevede che la stringa non possa iniziare con un numero.

Credo che la cosa migliore sia quella validare tutti i messaggi XML in entrata con gli schemi XSD di SAML, in *aggiunta* agli altri controlli che facciamo.

**Comment by fmarco** [comment]
@alexrj sì, concordo. Come avevo indicato nelle note della PR per la validazione login, l'idea è di aggiungere un livello di controllo iniziale che si occupi solo di fare il match con gli schemi XSD, successivamente si fa il parsing più articolato.

**Comment by alexrj** [comment]
Io in realtà invertirei i controlli: prima i controlli custom, e poi se vanno a buon fine usiamo lo schema XSD. Questo perché i messaggi restituiti dai controlli dello schema sono molto criptici e poco comprensibili, e c'è sovrapposizione tra quelli custom e quelli XSD per cui darei priorità a quelli custom che hanno messaggi di errore scritti bene. Che ne pensi?

**Comment by fmarco** [comment]
@alexrj sì, forse ha senso invertire l'ordine, pensavo a validare prima gli xsd solo se i test che sto facendo con alcune librerie danno un esito positivo (ad es. con questa https://github.com/brunato/xmlschema potremmo ottenere un dizionario da utilizzare per "mergiare" la validazione custom dell'applicazione).

**Comment by alexrj** [comment]
Ho aperto una issue separata per la validazione con XSD.

Questa issue resta aperta per verificare, dopo che avremo introdotto la validazione XSD, che l'ID sia correttamente validato e che il messaggio di errore sia chiaro - in caso contrario dovremo introdurre un controllo manuale.

**Comment by fmarco** [comment]
@alexrj gestita e testata dalla validazione XSD

**Comment by alexrj** [comment]
Confermo, attualmente compare in questo modo:

![screen shot 2018-08-10 at 21 42 02](https://user-images.githubusercontent.com/594957/43978049-3f91d5c8-9ce6-11e8-9bf0-8f753b47d874.png)

Però mettiamoci nei panni dell'utente. Di fronte a questo errore si metterà a cercare su Google cosa vuol dire _"un valore valido di tipo atomico xs:ID"_ e farà molta fatica a trovare il documento che lo specifica. Veniamogli incontro con una ulteriore validazione mirata all'errore più frequente:

* _Il valore dell'attributo ID può iniziare solo con una lettera o con un underscore._

**Comment by sanjioh** [comment]
Modifca eseguita in #124.
Attualmente il messaggio completo risulta essere:
`Elemento '{urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest', attributo 'ID': Il valore dell'attributo 'ID' può iniziare solo con una lettera o con un underscore.`
Può andar bene oppure intendevi fornire la nuova stringa *in aggiunta* all'errore precedente?

**Comment by sanjioh** [comment]
Corretto in master con il messaggio generale.

**Comment by fmarco** [comment]
@alexrj questa si può chiudere?
