### ISSUE TITLE
AuthnRequest: ProtocolBinding non viene validato correttamente

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#65]
Ho mandato via HTTP-Redirect una AuthnRequest contenente `ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"` e non ho ricevuto segnalazioni di errore.

**Comment by fmarco** [comment]
@alexrj ProtocolBinding però non si riferisce al binding da utilizzare per inoltrare la risposta?

**Comment by alexrj** [comment]
Hai ragione, questa issue mi è sfuggita di mano! :)
