### ISSUE TITLE
Response/Assertion: Rimuovere <AuthenticatingAuthority>

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv2#68]
Nelle asserzioni viene restituito un tag `<AuthenticatingAuthority>` contenente lo stesso valore di `<AuthnContextClassRef>`:

```xml
		<ns1:AuthnStatement AuthnInstant="2018-07-12T14:37:14Z" SessionIndex="id-66lDkmZaeR6EOj9Au">
			<ns1:AuthnContext>
				<ns1:AuthnContextClassRef>
					https://www.spid.gov.it/SpidL1
				</ns1:AuthnContextClassRef>
				<ns1:AuthenticatingAuthority>
					https://www.spid.gov.it/SpidL1
				</ns1:AuthenticatingAuthority>
			</ns1:AuthnContext>
		</ns1:AuthnStatement>
```

Oltre ad essere semanticamente scorretto, perché quel campo dovrebbe contenere un altro tipo di informazione, credo sia opportuno toglierlo visto che non è previsto dalle regole SPID e qualcuno farci affidamento per leggere il livello SPID che invece è indicato solo in `<AuthnContextClassRef>`.

**Comment by fmarco** [comment]
@alexrj adesso non viene più inserita nelle response, ho aggiunto anche un test di verifica

**Comment by fmarco** [comment]
@alexrj si può chiudere?
