### ISSUE TITLE
Container docker esce all'avvio

### ISSUE THREAD

**Issue by marcoz-tsn** [italia/spid-testenv2#73]
OS: Windows 10 Pro
Docker: 18.03
Eseguite istruzioni del README ai capitoli:
- Configurazione
- Installazione / Docker

Al comando 
`docker start spid-testenv2`
il container esce con valore 0.
Chiedo cortesemente indicazioni, grazie!

**Comment by alexrj** [comment]
E non è partito? `docker start` lancia il container in background e il valore 0 solitamente indica l'assenza di errori. Non risulta in `docker ps`?

**Comment by marcoz-tsn** [comment]
No, in `docker ps` non risulta, nonostante l'exit code. Nemmeno il log di docker contiene errori o warning...

**Comment by marcoz-tsn** [comment]
Salve, non ho più avuto notizie, quindi ho riprovato ma invece di creare direttamente il container come indicato nel README, ho creato l'immagine usando il Dockerfile, lanciando comando da una shell aperta in radice del repo decompresso:
`docker build -t spid-testenv2 .`
e poi creando il container con:
`docker run -it --name spid-testenv2 --mount src="path\to\spid-testenv2\conf",target="/app/conf",type=bind -p 8088:8088 spid-testenv2`

Il container esce ancora, ma almeno mi viene restituito il messaggio: 

> Chiave privata dell'IdP di test non trovata: idp.key non trovato

E' un progresso o era "meglio" prima? Spero di avere qualche indicazione, grazie di nuovo.

**Comment by marcoz-tsn** [comment]
Salve, a beneficio di tutti specifico che il problema in ogni caso è la configurazione dei nomi dei vari file indicati in config.yaml. Non si tratta di un nome ma di un percorso completo, e va specificato relativamente alla posizione del file spid-testenv.py (/app).
Quindi, se nell'esempio è presente semplicemente:
`key_file: "idp.key"`
il settaggio funzionante è:
`key_file: "./conf/idp.key"`

Stessa cosa per il file di certificato e quello/i di metadati SP.

Happy SPIDing!

**Comment by alexrj** [comment]
Grazie per il contributo @marcoz-tsn! Il file di esempio è stato aggiornato con i path corretti come da te indicato.

**Comment by alexrj** [comment]
(A beneficio di altri utenti aggiungo che con il comando `docker logs spid-testenv2` si può vedere l'output del testenv2 nel container per leggere eventuali errori come questo)
