### ISSUE TITLE
AuthnRequest: validazione di RequestedAuthnContext produce messaggio di errore non chiaro

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#79]
Inviando questa AuthnRequest:

```xml
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Destination="http://localhost:8088/sso" ForceAuthn="false" IssueInstant="2018-07-19T09:58:21Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0" ID="88507252ddfbd95b57c3ccb15058abf8">
  <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://localhost/">https://localhost/</saml2:Issuer>
  <saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
  <saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef>
</saml2p:AuthnRequest>
```

ottengo la seguente schermata di errore:

![screen shot 2018-07-19 at 13 09 02](https://user-images.githubusercontent.com/594957/42939131-ed4d32aa-8b54-11e8-9199-5248e0f76f4d.png)

Oltre alla dicitura "Esempio" che mi sembra un refuso, si dice che l'elemento `<saml:AuthnContext>` è obbligatorio. Questo però non è vero. Semmai l'elemento mancante in questa richiesta è `<RequestedAuthnContext>`.

**Comment by fmarco** [comment]
@alexr la parter "Esempio ..." è un'informazione addizionale che ho pensato di inserire nella parte di validazione per rendere noto all'utente come impostare quel framento di messaggio SAML2, eventualmente anche come stringhe di settings da mettere da qualche parte.
Su RequestedAuthnContext hai ragione, appena carico le modifiche per validare tramite xsd questi casi non dovrebbero presentersi più (bisognerà poi fare di test adeguati).

**Comment by alexrj** [comment]
Io toglierei per adesso questa stringa `<br>Esempio:<br>` visto che è vuota. Poi magari in una issue separata ragioniamo su come uniformare e migliorare i messaggi di errore.

Lasciamo aperta questa issue in attesa della validazione XSD.

**Comment by fmarco** [comment]
@alexrj rimosse stringhe di esempio

**Comment by fmarco** [comment]
@alexrj questo errore adesso è coperto dalla validazione, ho aggiunto anche un test

**Comment by alexrj** [comment]
Attualmente appare così:

![screen shot 2018-08-10 at 21 39 44](https://user-images.githubusercontent.com/594957/43977957-f05debfe-9ce5-11e8-9224-c7df128868bf.png)

La prima parte è corretta. Ma la seconda non lo è, perché sembra dire che è obbligatorio un tag `< AuthnContext>` che invece qui non esiste. L'utente andrà nella documentazione a cercarlo e non lo troverà...

**Comment by fmarco** [comment]
@alexrj typo corretto
