### ISSUE TITLE
AuthnRequest: non viene rilevata l'assenza di AssertionConsumerServiceIndex e AssertionConsumerServiceURL

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#80]
La seguente AuthnRequest viene accettata dal testenv2 senza che siano rilevati errori:

```xml
<saml2p:AuthnRequest Destination="http://localhost:8088/sso" ForceAuthn="false" Version="2.0" IssueInstant="2018-07-19T11:17:22Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" ID="29f66d989143c748ab9dd1c13fbee7f0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://localhost/">https://localhost/</saml2:Issuer><saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"></saml2p:NameIDPolicy><saml2p:RequestedAuthnContext Comparison="exact"><saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext></saml2p:AuthnRequest>
```

In realtà questa richiesta non è valida perché manca dell'attributo `AssertionConsumerServiceIndex` e dell'attributo `AssertionConsumerServiceURL`. Uno dei due è richiesto obbligatoriamente dalle regole tecniche.

Nota: è necessario riportare come errore anche il caso in cui siano presenti entrambi (sono mutuamente esclusivi).

**Comment by fmarco** [comment]
@alexrj Quello che scrivevo qua è corretto quindi? https://github.com/italia/spid-testenv2/issues/43 

Confermi che è o uno o l'altro?

**Comment by fmarco** [comment]
@alexrj pushato un fix su master

**Comment by fmarco** [comment]
@alexrj aggiunti tests
