### ISSUE TITLE
LogoutResponse ritornato con binding HTTP-Redirect incorrettamente firmato

### ISSUE THREAD

**Issue by simevo** [italia/spid-testenv2#88]
![screenshot_20180724_175432](https://user-images.githubusercontent.com/8254819/43150795-197599c0-8f6b-11e8-94ef-3e578e0a021a.png)

ma secondo l'avviso 3 pagina 9:
> nel caso del binding SOAP e HTTP POST deve essere presente l’elemento <Signature>
contenente la firma sulla risposta apposta dell’entità emittente

quindi la firma dovrebbe essere passata come parametro risposta

**Comment by alexrj** [comment]
Sì, esatto, nel caso del binding HTTP-Redirect la firma deve essere passata in query string e non nella risposta XML.

**Comment by alexrj** [comment]
A me risulta corretto. @simevo puoi confermare?

@fmarco abbiamo un regression test?

**Comment by simevo** [comment]
100 % OK con spid-php2 (trovati tanti bug dalla ns parte per riprodurre !)

![screenshot_20180811_113810](https://user-images.githubusercontent.com/8254819/43990337-2d5f1cc4-9d5b-11e8-94ee-3b8a4cdd5679.png)

**Comment by fmarco** [comment]
@alexrj aggiunti tests

**Comment by alexrj** [comment]
Perfetto, chiudo
