### ISSUE TITLE
Response/Assertion: firma non valida?

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv2#91]
Sto avendo problemi a verificare la firma delle asserzioni generate dal testenv2. Potrei essere io a sbagliare qualcosa.

Oltre alla mia implementazione (che ovviamente potrebbe avere un bug) la verifica mi fallisce usando questo tool online: https://www.samltool.com/validate_response.php

Fallisce inoltre usando questo comando in locale:

```
$ xmlsec1 --verify --insecure --id-attr:ID "urn:oasis:names:tc:SAML:2.0:assertion:Assertion" response.xml
```

Sia con la mia implementazione sia con xmlsec1 il problema è che il calcolo del digest fallisce.

Guardando il codice, ed in particolare `login()` dalla riga 1251, ho l'impressione che l'asserzione venga generata e firmata, e poi venga alterata per fare aggiustamenti sugli attributi. È così? Se così fosse spiegherebbe il digest errato, perché ovviamente una volta firmata l'asserzione non si possono fare modifiche.

**Comment by fmarco** [comment]
@alexrj errore mio, avevo lasciato fuori la logica di sovrascrittura di gestione degli attributi, adesso ho spostato tutto in alcuni override su alcuni componenti custom di pysaml2. Riprova pure.

**Comment by alexrj** [comment]
Ora funziona, grazie!
