### ISSUE TITLE
Errore "Parametro SAMLRequest assente." utilizzando i SP del repo spid-dotnet-sdk

### ISSUE THREAD

**Issue by marcoz-tsn** [italia/spid-testenv2#99]
Salve, non sembra possibile effettuare l'autenticazione utilizzando uno qualsiasi dei progetti AspNet che implementano un SP di test contenuti nel repository italia / spid-dotnet-sdk.
L'errore restituito dalla pagina /sso dell'IdP è:
![image](https://user-images.githubusercontent.com/10044374/43585082-7b396d26-9664-11e8-8e4f-7dde8bdc1f05.png)

Prendendo per esempio Italia.Spid.AspNet.WebApp, vedo che la view Home/PostData.cshtml contiene effettivamente un input denominato SAMLRequest, il cui valore è la richiesta SAML2 strutturata in xml e codificata in base64; quindi è un parametro di form.
Il problema, mi pare, sta nel file **spid-testenv.py**, nel metodo `single_sign_on_service(self)`: l'istruzione
`saml_msg = self.unpack_args(request.args)`
**si aspetta che il parametro SAMLRequest sia passato in query string** in ogni caso, e anche la gestione del
`binding = BINDING_HTTP_POST`
lo deriva dalla stessa origine.

Non mi intendo di python quindi potrei aver capito male; in ogni caso sarebbe auspicabile che lo spid-dotnet-sdk funzionasse con questo ambiente spid di test proprio come funzionava con quello precedente.
Any help appreciated!

**Comment by fmarco** [comment]
@marcoz-tsn Potresti riprovare con l'ultima versione di master?

**Comment by marcoz-tsn** [comment]
Scusa l'attesa, ci ho messo un po' ad applicare correttamente il .py aggiornato. Il problema segnalato è risolto anche se ricevo un errore nella validazione della richiesta authn:


Elemento | Dettagli errore
-- | --
samlp:NameIDPolicy | AllowCreateL'attributo non è richiesto

**Comment by fmarco** [comment]
@marcoz-tsn grazie a te!

**Comment by marcoz-tsn** [comment]
Ho appena pullato l'ultima versione e provando l'autenticazione ricevo nuovamente l'errore in oggetto.
Ora poi non trovo il messaggio "Parametro SAMLRequest assente" in nessun file .py, quindi non ho idea di dove cercare..

Un aiutino?

**Comment by alexrj** [comment]
Ho appena provato ad inviare una AuthnRequest via HTTP-POST con l'attuale master, e funziona.

@marcoz-tsn, stai usando l'attuale master?
Potresti postare i contenuti del log del testenv2 per vedere esattamente cosa arriva?

**Comment by marcoz-tsn** [comment]
Ho risolto eseguendo questi passaggi:
- pull ultima versione di spid-testenv2
- ricreazione container docker previa esecuzione di
`docker image rm italia/spid-testenv2`
- modifica della funzione **BuildAuthnPostRequest** del progetto **Italia.Spid.Authentication**, sostituendo:
`AttributeConsumingServiceIndex = 1` con:
`AttributeConsumingServiceIndex = 0`
